### ISSUE TITLE
filter stacktraces broken

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1219]
When inspecting test failures in the test plugin even though I have filter stacktraces turned on I still get a load of crufty stackframes included at the bottom of the stacktrace. Specifically I think all of these should be filtered out, no?

at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.$call$(AppliedFunction.java:246)
	at com.redhat.ceylon.compiler.java.Util.apply(Util.java:1352)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.apply(Metamodel.java:1578)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:398)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:234)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:223)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:216)
	at ceylon.test.core.DefaultTestExecutor.invokeFunction$priv$(DefaultTestExecutor.ceylon:228)
	at ceylon.test.core.DefaultTestExecutor.access$100(DefaultTestExecutor.ceylon:227)
	at ceylon.test.core.DefaultTestExecutor$4.$call$(DefaultTestExecutor.ceylon:196)
	at ceylon.test.core.DefaultTestExecutor$2.$call$(DefaultTestExecutor.ceylon:163)
	at ceylon.test.core.DefaultTestExecutor$3.$call$(DefaultTestExecutor.ceylon:170)
	at ceylon.test.core.DefaultTestExecutor$1.$call$(DefaultTestExecutor.ceylon:146)
	at ceylon.test.core.DefaultTestExecutor.execute(DefaultTestExecutor.ceylon:32)
	at ceylon.test.core.DefaultTestRunner$5$1.next(DefaultTestRunner.ceylon:60)
	at ceylon.language.Array.createArrayFromIterable(Array.java:116)
	at ceylon.language.Array.<init>(Array.java:100)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:230)
	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
	at ceylon.test.core.DefaultTestRunner.run(DefaultTestRunner.ceylon:60)
	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:84)
	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:36)
	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:104)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:170)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:154)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:215)
	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:173)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:409)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)

**Comment by thradec** [comment]
Fixed via fdf71fa, thanks @tombentley for notice.
