### ISSUE TITLE
CCE when dragging file from source to root folder

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon-ide-eclipse#1227]
When dragging a `.ceylon` source file out of the source folder into the root folder of the project:

```
java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.core.resources.IFolder
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.incrementalBuild(CeylonBuilder.java:1730)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.access$2(CeylonBuilder.java:1642)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:961)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:1)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:234)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:958)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
```

**Comment by gavinking** [comment]
@davidfestal one for you, I suppose.
