### ISSUE TITLE
CCE: Value cannot be cast to JavaBeanValue

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1237]
From time to time, when working in the IDE, I get a CCE:

```
java.lang.ClassCastException: com.redhat.ceylon.compiler.typechecker.model.Value cannot be cast to com.redhat.ceylon.compiler.loader.model.JavaBeanValue
   at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2141)
   at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:1892)
   at com.redhat.ceylon.compiler.loader.model.LazyClass.load(LazyClass.java:110)
   at com.redhat.ceylon.compiler.loader.model.LazyClass.getExtendedTypeDeclaration(LazyClass.java:209)
   at com.redhat.ceylon.compiler.loader.model.LazyClass.getExtendedTypeDeclaration(LazyClass.java:49)
   at com.redhat.ceylon.eclipse.code.outline.CeylonHierarchyContentProvider$Runnable.run(CeylonHierarchyContentProvider.java:381)
   at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by davidfestal** [comment]
The problem can be reproduced by trying to load this Java code from the modelLoader (from binaries):
```Java
package issue1216;

public class Issue1237 {
	public class Inner {
	}
	
	public Issue1237(Inner anyParamName) {
	}
	
	public void setInner(String anySetterParamName) {
	}
}
```

Let me explain what I've debugged and observed : since the type of the `anyParamName` constructor parameter is `Inner`, the model loader gives the name `inner` to the parameter itself.

Then, when iterating through the setters during class completion [here](https://github.com/ceylon/ceylon-compiler/blob/master/src/com/redhat/ceylon/compiler/loader/AbstractModelLoader.java#L2149), it finds a declaration with the same name as the field name derived from the setter : it is the constructor parameter value, which, of course, is not a `JavaBeanValue`, since method parameters are loaded by the model loader as simple `Value` objects.

By the way it seems a bit strange to me that, in line [2173](https://github.com/ceylon/ceylon-compiler/blob/master/src/com/redhat/ceylon/compiler/loader/AbstractModelLoader.java#L2173), we check whether `decl`is an instance of `JavaBeanValue` whereas just before, in line [2160](https://github.com/ceylon/ceylon-compiler/blob/master/src/com/redhat/ceylon/compiler/loader/AbstractModelLoader.java#L2160), we assume that it is. But, of course, I don't fully know the whole context.  

@FroMage , @quintesse : should I open a ceylon-compiler issue referencing this one ?

**Comment by FroMage** [comment]
Thanks, Fixed.
