### ISSUE TITLE
Exception Popup during build is the overrides.xml miss some information

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1295]
If the overrides.xml file contains a <set> tag without the module attribute, the following uncatched Exception occurs during  the build  :

```
java.lang.IllegalArgumentException: Missing 'module' attribute in element [set: null].
	at com.redhat.ceylon.cmr.api.Overrides.getRequiredAttribute(Overrides.java:397)
	at com.redhat.ceylon.cmr.api.Overrides.getArtifactContext(Overrides.java:367)
	at com.redhat.ceylon.cmr.api.Overrides.parse(Overrides.java:238)
	at com.redhat.ceylon.cmr.api.Overrides.parse(Overrides.java:197)
	at com.redhat.ceylon.cmr.api.AbstractRepositoryManager.<init>(AbstractRepositoryManager.java:45)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.<init>(AbstractNodeRepositoryManager.java:69)
	at com.redhat.ceylon.cmr.impl.RootRepositoryManager.<init>(RootRepositoryManager.java:58)
	at com.redhat.ceylon.cmr.impl.RepositoryManagerBuilderImpl.<init>(RepositoryManagerBuilderImpl.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.redhat.ceylon.cmr.api.RepositoryManagerBuilder.<init>(RepositoryManagerBuilder.java:74)
	at com.redhat.ceylon.cmr.ceylon.CeylonUtils$CeylonRepoManagerBuilder.buildManagerBuilder(CeylonUtils.java:317)
	at com.redhat.ceylon.cmr.ceylon.CeylonUtils$CeylonRepoManagerBuilder.buildManager(CeylonUtils.java:275)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.resetProjectRepositoryManager(CeylonBuilder.java:3252)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.getProjectRepositoryManager(CeylonBuilder.java:3236)
	at com.redhat.ceylon.eclipse.code.navigator.CeylonNavigatorContentProvider.getProjectRepositoryNodes(CeylonNavigatorContentProvider.java:203)
	at com.redhat.ceylon.eclipse.code.navigator.CeylonNavigatorContentProvider.getPipelinedChildren(CeylonNavigatorContentProvider.java:76)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.getPipelinedChildren(SafeDelegateTreeContentProvider.java:178)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.pipelineChildren(NavigatorContentServiceContentProvider.java:206)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.pipelineChildren(NavigatorContentServiceContentProvider.java:210)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.access$1(NavigatorContentServiceContentProvider.java:192)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$1.run(NavigatorContentServiceContentProvider.java:161)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.internalGetChildren(NavigatorContentServiceContentProvider.java:139)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.getChildren(NavigatorContentServiceContentProvider.java:125)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1365)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:353)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:905)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:617)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2647)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1918)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1925)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1893)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1850)
	at org.eclipse.ui.navigator.CommonViewer.internalRefresh(CommonViewer.java:561)
	at org.eclipse.jface.viewers.StructuredViewer$8.run(StructuredViewer.java:1528)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1436)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1397)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1525)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:533)
	at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:353)
	at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:510)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider$3.run(ResourceExtensionContentProvider.java:301)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider.runUpdates(ResourceExtensionContentProvider.java:312)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider.access$1(ResourceExtensionContentProvider.java:310)
	at org.eclipse.ui.internal.navigator.resources.workbench.ResourceExtensionContentProvider$1.run(ResourceExtensionContentProvider.java:134)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by davidfestal** [comment]
In the context of the IDE, we need a `RepositoryManager` for a project, even if the `overrides.xml` file is not valid.
Systematically throwing an exception in the `AbstractRepositoryManager` constructor when the `overrides.xml` is somehow invalid, makes things difficult to manage inside the IDE.

Inside the IDE, we should not throw the exception, still create a `RepositoryManager`, but catch the fact that the `Overrides` in invalid and add a global build error on the project, in order to make builds fail. 

I might be able to do this by using a derived `RepositoryManagerBuilderImpl` that creates a derived `RootRepositoryManager` (using the `ceylon.module.resolver.builder` system property available in the `RepositoryManagerBuilder`)

However I wonder if it wouldn't be nicer to add an API to `RepositoryManager` in order to be able to define what to do on a `Overrides`-related exception.

@FroMage : what is your preferred solution ?

**Comment by FroMage** [comment]
Sure, I guess we can change the API so that the `RepositoryManager` takes a built `Overrides` rather than just a file name, and then it's up to you to parse it and render errors.

**Comment by davidfestal** [comment]
Yes, it would be cool. Do you want me to do it ?

**Comment by davidfestal** [comment]
Let me do it then.

**Comment by FroMage** [comment]
Sure, I guess we can change the API so that the `RepositoryManager` takes a built `Overrides` rather than just a file name, and then it's up to you to parse it and render errors.

**Comment by FroMage** [comment]
Sure, I guess we can change the API so that the `RepositoryManager` takes a built `Overrides` rather than just a file name, and then it's up to you to parse it and render errors.

**Comment by FroMage** [comment]
Sure, I guess we can change the API so that the `RepositoryManager` takes a built `Overrides` rather than just a file name, and then it's up to you to parse it and render errors.

**Comment by davidfestal** [comment]
@FroMage : done in ceylon/ceylon-module-resolver@4916e95fc142005bed6ed7d09e6a78f7ad190ffb and ceylon/ceylon-module-resolver@839d88f15e272a54391c2e6ff2879ef20714e298
