### ISSUE TITLE
NPE when debugging is some Ceylon source code with the Expressions View opened

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1301]
When debugging a Ceylon source file, if the Expressions View is opened and contains Java watches, this triggers a NPE with an error popup : 
```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.getTypeName(SourceBasedSourceGenerator.java:783)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.buildMethodDeclaration(SourceBasedSourceGenerator.java:478)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.buildBody(SourceBasedSourceGenerator.java:419)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.buildTypeBody(SourceBasedSourceGenerator.java:360)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.buildTypeDeclaration(SourceBasedSourceGenerator.java:645)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.SourceBasedSourceGenerator.endVisit(SourceBasedSourceGenerator.java:1088)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:473)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.EvaluationSourceGenerator.createEvaluationSourceFromSource(EvaluationSourceGenerator.java:152)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.EvaluationSourceGenerator.getSource(EvaluationSourceGenerator.java:233)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine.getCompiledExpression(ASTEvaluationEngine.java:319)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine.evaluate(ASTEvaluationEngine.java:131)
	at org.eclipse.jdt.internal.debug.ui.JavaWatchExpressionDelegate$EvaluationRunnable.run(JavaWatchExpressionDelegate.java:142)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run(JDIThread.java:3158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
``` 
In fact the problem is that JDT doesn't look at the source file name to be sure this is Java code. and it tries to evaluate the watch expressions against the Ceylon source code, thinking it is Java code.
Since this pre-requisites are not met, finally a NPE is thrown.

It seems that the very root cause of this is that the Stratum in which the source file name and lines are added is the default stratum (ie. the Java stratum). This was also the real root cause of #1254.

@quintesse, @FroMage, @tombentley : Sometimes I think that, to avoid such bad surprises in the future, we should have used a `Ceylon` stratum to generate the `source name`, `source path` and all the debug information in the class files generated from Ceylon sources (and of course set the default stratum to `Ceylon` for those files).
See https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/Location.html and https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/ReferenceType.html#defaultStratum() for reference information about that.

This would be the best way to solve this issue.

**Comment by tombentley** [comment]
Yeah, I'm aware of the JDI stratum thing and I've thought we should set it before, but I don't know how it corresponds to anything in the `.class` file format. Any references?

**Comment by davidfestal** [comment]
@tombentley : I'm looking into it right now

**Comment by quintesse** [comment]
According to this http://stackoverflow.com/questions/3423988/implement-different-stratum-for-java-debugger-interface strata are meant for languages that get compield to Java first before getting compiled to bytecode. Languages that get compiled directly don't need them it says.

**Comment by davidfestal** [comment]
@quintesse : I know yes, we discussed this a long time ago together. However in the case of Ceylon, it is converted to Java, not really Java source code, but at least a Javac AST. So maybe there is a way to use a Ceylon stratum.

**Comment by quintesse** [comment]
Maybe yes, but it seems that it is meant more for those cases where a location in the class file can refer to several sources files at once, so to distinguish between them you'd need the "stratum" in the class file. In this case though it might just be sufficient to configure that elsewhere so Eclipse knows a .ceylon file does not use the default "Java" stratum. (How I have no idea)

**Comment by tombentley** [comment]
JSR45 seems to hold the missing pieces of the puzzle, and it does seem to assume a translator which emits java source code which is then passed to a java compiler. If the translator can also emit a source map then the .class file can be augmented with the `SourceDebugExtension`.

Our compiler doesn't fit in to this entirely comfortably because while we can pretty print the AST, that AST often has things in that javac would reject. For debugging purposes I'm not sure how much that matters, but:

* if we went emitting this stuff do we know how that might affect other debuggers? We could be fixing some bugs when debugging eclipse, only to make life harder when debugging with something else.
* as far I understand JDI, it's possible (at least in theory) to select the stratum you which to debug at, and I'm pretty sure that possibility isn't really one we want to get into

**Comment by davidfestal** [comment]
It's just a pity that you cannot reset the *default* stratum of a file to some other stratum, without adding a `SourceDebugExtension` attribute that contains source to source mappings.
Just to say that the source code is *not* Java.

**Comment by tombentley** [comment]
Yeah, I completely agree!

**Comment by davidfestal** [comment]
From within the JSR45 spec : 

_A programming language implementor, directly generating class files might also choose to generate SMAPs (thus functioning as both language-processor and compiler) since the SMAP is useful for describing source configurations (such as multiple source files per class file) which cannot be represented with the SourceFile and LineNumberTable attributes. In this case, the input is translated-source and the final-source is represented in the attributes but is never generated._

So maybe we can do something :-)

**Comment by quintesse** [comment]
But isn't that perhaps done at some other level? Something that tells the system that a .ceylon file by default isn't the Java stratum?  If Eclipse debugs JRuby or Scala it must also somehow know that they are not Java, right?

**Comment by davidfestal** [comment]
Well, since I didn't find anything useful about that, let me fix this in Eclipse only.

**Comment by davidfestal** [comment]
In fact, more precisely this seems to come from the fact that Java-specific source mappers are associated to Ceylon archives. Nothing to do with strata in this case !

**Comment by quintesse** [comment]
Ah, that already sounds more logical :)

**Comment by davidfestal** [comment]
Now fixed.
