### ISSUE TITLE
Cannot create ceylon project on Windows platform

### ISSUE THREAD

**Issue by eugenpp** [ceylon/ceylon-ide-eclipse#1304]
The problem is at CeylonClasspathUtil.java:283. Split pattern should be escaped. 
For windows platform it contains metacharacter "\".

```
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 7
ceylon\language\1.1.1\
       ^
	at java.util.regex.Pattern.error(Pattern.java:1924)
	at java.util.regex.Pattern.escape(Pattern.java:2416)
	at java.util.regex.Pattern.atom(Pattern.java:2164)
	at java.util.regex.Pattern.sequence(Pattern.java:2097)
	at java.util.regex.Pattern.expr(Pattern.java:1964)
	at java.util.regex.Pattern.compile(Pattern.java:1665)
	at java.util.regex.Pattern.<init>(Pattern.java:1337)
	at java.util.regex.Pattern.compile(Pattern.java:1022)
	at java.lang.String.split(String.java:2313)
	at java.lang.String.split(String.java:2355)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonClasspathUtil.javaSourceArchivePath(CeylonClasspathUtil.java:283)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonClasspathUtil.ceylonSourceArchiveToJavaSourceArchive(CeylonClasspathUtil.java:306)
```

**Comment by davidfestal** [comment]
It should work now. @eugenpp : Can you confirm before I close the issue ?

**Comment by eugenpp** [comment]
Solved.
