### ISSUE TITLE
un-shared unit tests on JavaScript

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1321]
Create a simple project with I have a simple JavaScript project in Eclipse with a simple unit test

```ceylon

import ceylon.test {
    test,
    assertTrue
}

test
void testMe() {
    assertTrue(true);
}

```

This works if I compile the project and then run the unit test with the command line tools:

${PATH_TO_GITHUB_DIST}/bin/ceylon compile-js 
${PATH_TO_GITHUB_DIST}/bin/ceylon run-js luke.hellonodejs/1.1.1
${PATH_TO_GITHUB_DIST}/bin/ceylon test-js luke.hellonodejs/1.1.1

However, it fails when right-clicking and Run As > Ceylon Test JavaScript with the following output and error:

```
NODE_PATH=${ECLIPSE_DIR}/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150408-1219/repo:${ECLIPSE_WORKSPACES_DIR}/ceylon_dev/NodeJsTest/modules:${HOME_DIR}/.ceylon/repo:${HOME_DIR}/.ceylon/cache:[Maven] Aether:${ECLIPSE_WORKSPACES_DIR}/ceylon_dev/NodeJsTest/modules
${ECLIPSE_DIR}/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150408-1219/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6339
if (mm.t) {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (${ECLIPSE_DIR}/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150408-1219/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6339:7)
    at atr$.mod [as qualifiedName] (${ECLIPSE_DIR}/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150408-1219/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:5653:207)
    at findCandidatesInFunction$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1868:57)
    at findCandidatesInFunctionLiteral$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2060:1)
    at findCandidatesInTypeLiteral$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1928:4)
    at findCandidates$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1807:1)
    at createExecutors$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1600:10)
    at defaultTestRunner$.$37h (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1520:8)
    at DefaultTestRunner$core (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1473:45)
    at Object.createTestRunner (${HOME_DIR}/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1055:8)
```

If I run the unit test by either right clicking on the module or the package, the NODE_PATH is output but nothing happens.

**Comment by thradec** [comment]
@chochos can you take a look, please

**Comment by chochos** [comment]
As soon as I can run the Ceylon IDE from my Eclipse...

**Comment by gavinking** [comment]
I can't reproduce this, and given that this problem was reported back in April, I'll assumed it's fixed.

@sgalles please confirm. Thanks.

**Comment by lukedegruchy** [comment]
Still failing for me.   I just pulled from github tonight using the new procedures to build the IDE.

The Ceylon file for the unit test is the same as the one in the bug description.

If I right-click on the package with the unit test, I see only the following in the console but no green or red line in the Ceylon Test panel:

```
NODE_PATH=/Applications/eclipse/4.5/ceylon_dev/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2355/repo:/Users/luke/Development/ides/eclipse/workspaces/mars_ceylon_dev/NodeJsTest/modules:/Users/luke/.ceylon/repo:/Users/luke/.ceylon/cache:[Maven] Aether:/Users/luke/Development/ides/eclipse/workspaces/mars_ceylon_dev/NodeJsTest/modules
```

However, if I right-click on the ceylon file for the unit test, it fails more obviously:

```
NODE_PATH=/Applications/eclipse/4.5/ceylon_dev/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2355/repo:/Users/luke/Development/ides/eclipse/workspaces/mars_ceylon_dev/NodeJsTest/modules:/Users/luke/.ceylon/repo:/Users/luke/.ceylon/cache:[Maven] Aether:/Users/luke/Development/ides/eclipse/workspaces/mars_ceylon_dev/NodeJsTest/modules
/Applications/eclipse/4.5/ceylon_dev/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2355/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6307
if (mm.t==='u' || mm.t==='i') {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (/Applications/eclipse/4.5/ceylon_dev/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2355/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6307:7)
    at atr$.mod [as qualifiedName] (/Applications/eclipse/4.5/ceylon_dev/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2355/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:10515:207)
    at findCandidatesInFunction$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1065:57)
    at findCandidatesInFunctionLiteral$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1186:1)
    at findCandidatesInTypeLiteral$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1107:4)
    at findCandidates$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1031:1)
    at createExecutors$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:901:10)
    at defaultTestRunner$.$38b (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:860:8)
    at DefaultTestRunner$core (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:833:45)
    at Object.createTestRunner (/Users/luke/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2166:8)
```

**Comment by gavinking** [comment]
> If I right-click on the package with the unit test, I see only the following in the console but no green or red line in the Ceylon Test panel:

Well that's a totally separate issue (#1495).

**Comment by gavinking** [comment]
Wait. Your `testMe()` method isn't `shared`.

**Comment by gavinking** [comment]
OK, so now I _can_ reproduce it, if the test method is un-`shared`.

**Comment by gavinking** [comment]
I have changed the issue description to properly reflect the problem. @chochos @thradec could you guys decide what is the right thing to do here, please? Are `test` functions supposed to be `shared`? If not, that's probably a problem for JS.

Whatever, it's _definitely not OK_ that we get runtime failures like this:

```
/Applications/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2337/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6307
if (mm.t==='u' || mm.t==='i') {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2337/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6307:7)
    at atr$.mod [as qualifiedName] (/Applications/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150918-2337/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:10515:207)
    at findCandidatesInFunction$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1065:57)
    at findCandidatesInFunctionLiteral$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1186:1)
    at findCandidatesInTypeLiteral$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1107:4)
    at findCandidates$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1031:1)
    at createExecutors$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:901:10)
    at defaultTestRunner$.$38b (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:860:8)
    at DefaultTestRunner$core (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:833:45)
    at Object.createTestRunner (/Users/gavin/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2166:8)
```

I mean, wtf is `mm.t`?

**Comment by chochos** [comment]
No, test methods don't have to be shared. Actually the unshared test method runs fine with `ceylon test-js` on CLI, so this is probably related to some outdated module in the IDE (either the language module, or `ceylon.test` or something)

**Comment by chochos** [comment]
did the test API change? If it did, was it updated on the IDE for JS?

**Comment by sgalles** [comment]
> @sgalles please confirm. Thanks

I assume that was for @lukedegruchy obviously

**Comment by gavinking** [comment]
Yes, of course. Sorry.

**Comment by FroMage** [comment]
@thradec, @chochos  any idea how we can resolve this?

**Comment by FroMage** [comment]
The weird thing is the same runs from the CLI.

**Comment by FroMage** [comment]
Latest stack trace from the IDE is:

```
NODE_PATH=/home/stephane/no-backup/src/eclipse-mars/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151009-1031/repo:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/test-deps:/home/stephane/.ceylon/repo:/home/stephane/.ceylon/cache:[Maven] Aether:/home/stephane/src/java-eclipse/ceylon-sdk/modules

/home/stephane/no-backup/src/eclipse-mars/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151009-1031/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6678
if (mm.t==='u' || mm.t==='i') {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (/home/stephane/no-backup/src/eclipse-mars/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151009-1031/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6678:7)
    at $init$OpenFunction$jsint.atr$.mod [as qualifiedName] (/home/stephane/no-backup/src/eclipse-mars/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151009-1031/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:9643:207)
    at findCandidatesInFunction$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1575:57)
    at findCandidatesInFunctionLiteral$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1715:1)
    at findCandidatesInTypeLiteral$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1622:4)
    at findCandidates$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1523:1)
    at createExecutors$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1376:10)
    at $init$DefaultTestRunner$core.defaultTestRunner$.$wgb9lg$zvl (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1328:8)
    at DefaultTestRunner$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1298:52)
    at Object.createTestRunner (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:247:8)
ceylon test-js: Node process exited with non-zero exit code: 8
```

**Comment by FroMage** [comment]
From that stack trace I can see that I'm not using outdated `ceylon.language` or `ceylon.test` modules.

**Comment by FroMage** [comment]
Actually no, all this is a distraction. It fails in the IDE only if I run a single test. AND it fails in the CLI for that single test just as well:

```
atlantis stephane 14:55 ceylon-sdk $ ../ceylon-dist/dist/bin/ceylon test-js --test test.ceylon.collection::f test.ceylon.collection
NODE_PATH=/home/stephane/src/java-eclipse/ceylon-dist/dist/repo:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/test-deps:/home/stephane/.ceylon/repo:/home/stephane/.ceylon/cache:[Maven] Aether:/home/stephane/src/java-eclipse/ceylon-sdk/modules

/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6678
if (mm.t==='u' || mm.t==='i') {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6678:7)
    at $init$OpenFunction$jsint.atr$.mod [as qualifiedName] (/home/stephane/src/java-eclipse/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:9643:207)
    at findCandidatesInFunction$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1575:57)
    at findCandidatesInFullQualifiedName$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1754:1)
    at findCandidatesInTypeLiteral$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1627:4)
    at findCandidates$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1523:1)
    at createExecutors$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1376:10)
    at $init$DefaultTestRunner$core.defaultTestRunner$.$wgb9lg$zvl (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1328:8)
    at DefaultTestRunner$core (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1298:52)
    at Object.createTestRunner (/home/stephane/src/java-eclipse/ceylon-sdk/modules/ceylon/test/1.1.1/ceylon.test-1.1.1.js:247:8)
ceylon test-js: Node process exited with non-zero exit code: 8
```

So it's indeed a metamodel bug, not related to the IDE. I will move it.

**Comment by FroMage** [comment]
Moved to https://github.com/ceylon/ceylon.language/issues/776

**Comment by FroMage** [comment]
OK so it works now.
