### ISSUE TITLE
Exception in the model Loader at initialization

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1322]
The followng exception is triggered during the classpath container initialization :
```
com.redhat.ceylon.compiler.loader.ModelResolutionException: The Model Loader corresponding to the type 'ceylon.language.$module_' was not available
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.doWithReferenceBinding(JDTModelLoader.java:825)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTClass.doWithBindings(JDTClass.java:382)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTClass.getAnnotation(JDTClass.java:323)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTClass.isAnnotationPresent(JDTClass.java:469)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTClass.isCeylon(JDTClass.java:488)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.newCompiledUnit(JDTModelLoader.java:1215)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.setModuleAndPackageUnits(JDTModelLoader.java:1177)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2232)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:1)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:249)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2065)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonProjectModulesContainer.resolveClasspath(CeylonProjectModulesContainer.java:309)
	at com.redhat.ceylon.eclipse.core.classpath.InitDependenciesJob.run(InitDependenciesJob.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```
This seems related to a race condition happening when many projects are opened.
It seems that the module descriptor class mirror retrieved during module validation for binary modules can sometimes come from another project that also contains this external archive. In this case, it might happen that the model loader of the other project is not already registered in the `JDTModelLoader` static loaders weak hash map.

**Comment by davidfestal** [comment]
Looking deeper into the JDT code confirms that the package fragment root used for an external jar in a `NameLookup` of a specific Java project, can indeed be a cached root from *another* project.
In other words external jar archive package fragment roots are shared across projects, which is *not* compatible with the way it's working  now.
I'll have to rework things again :-/
