### ISSUE TITLE
model loading problem with deprecated

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1333]
@davidfestal the model loader only just started to support `deprecated` properly. Now I'm seeing this error in the IDE:

```
com.redhat.ceylon.compiler.loader.ModelResolutionException: JDT reference binding without a JDT IType element !
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:1006)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.<init>(JDTType.java:201)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.toTypeMirror(JDTType.java:125)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.<init>(JDTType.java:152)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.<init>(JDTType.java:113)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod$3.doWithBinding(JDTMethod.java:230)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.doWithMethodBinding(JDTModelLoader.java:913)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod.doWithBindings(JDTMethod.java:295)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod.getReturnType(JDTMethod.java:226)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.isGetter(AbstractModelLoader.java:2580)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.isMethodOverloaded(AbstractModelLoader.java:2262)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2075)
	at com.redhat.ceylon.compiler.loader.AbstractModelLoader.complete(AbstractModelLoader.java:1909)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.load(LazyInterface.java:106)
	at com.redhat.ceylon.compiler.loader.model.LazyInterface.isDeprecated(LazyInterface.java:395)
	at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getDecorationAttributes(CeylonLabelProvider.java:1056)
	at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getDecorationAttributes(CeylonLabelProvider.java:989)
	at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getDecoratedImage(CeylonLabelProvider.java:150)
	at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getImageForDeclaration(CeylonLabelProvider.java:364)
	at com.redhat.ceylon.eclipse.code.complete.InvocationCompletionProposal.<init>(InvocationCompletionProposal.java:587)
	at com.redhat.ceylon.eclipse.code.complete.InvocationCompletionProposal.addReferenceProposal(InvocationCompletionProposal.java:115)
	at com.redhat.ceylon.eclipse.code.complete.CeylonCompletionProcessor.constructCompletions(CeylonCompletionProcessor.java:983)
	at com.redhat.ceylon.eclipse.code.complete.CeylonCompletionProcessor.getContentProposals(CeylonCompletionProcessor.java:442)
	at com.redhat.ceylon.eclipse.code.complete.CeylonCompletionProcessor$1Runnable.run(CeylonCompletionProcessor.java:233)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Would you take a look, please?

**Comment by davidfestal** [comment]
@gavinking : could you tell me more about this new support of `deprecated` ? Or give me some example code / project that would help me to reproduce the problem ?

**Comment by gavinking** [comment]
Well, we have a `deprecated` annotation, and the model has to reflect that. i.e. the model loader has to populate it.

**Comment by FroMage** [comment]
It looks like you're lazy-loading things more than in the past, I suppose, just to get that deprecated icon. Perhaps I can try to get you that deprecated attribute without loading the entire declaration? But only if you can confirm that it would save you lazy-loading (and that the same completion code would not lazy-load anyways for another attribute).

**Comment by gavinking** [comment]
Aaaah. I was wondering why autocompletion suddenly got slower! Yeah, I guess it must be that...

**Comment by davidfestal** [comment]
@gavinking : I was not able to reproduce the exception, even when trying to complete a deprecated binary declaration. Do you have a more detailed scenario or a precise declaration on which to run a test ?

**Comment by gavinking** [comment]
I have not seen this one recently, so probably it has been fixed. Closing.
