### ISSUE TITLE
editor/mouseover crash on large integer literals

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1338]
For something like:

```ceylon
void foo() {
    value a = 20_000_000_000;   
}
```

Mouseover on the number errors out, and sometimes the editor crashes.

```
!ENTRY org.eclipse.jface 4 2 2015-04-29 19:11:41.252
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NumberFormatException: For input string: "25214903917"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.getTermTypeHoverText(DocumentationHover.java:794)
        at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.getHoverText(DocumentationHover.java:643)
        at com.redhat.ceylon.eclipse.code.hover.DocumentationView.update(DocumentationView.java:196)
        at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.recomputeAnnotationsForSelection(MarkOccurrencesAction.java:242)
        at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.selectionChanged(MarkOccurrencesAction.java:156)
        at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
```

**Comment by gavinking** [comment]
Thanks, @jvasileff, should be fixed now.
