### ISSUE TITLE
Bad compile for JS only project

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1347]
Steps:

1) Create a new JavaScript only project in eclipse
2) Create a new module
3) Add to `module.ceylon` (be sure to include `test`):
```ceylon
module testjs "1.0.0" {
    import ceylon.test "1.1.1";
    import ceylon.collection "1.1.1";
}
```
4) Add to `run.ceylon`:
```ceylon
import ceylon.collection {
    ArrayList
}

shared void run() {
    print(ArrayList {"one", "two"});
}
```
5) Attempt to run:

```
/Users/jvasileff/Workspace-Ceylon/TesJS/modules/testjs/1.0.0/testjs-1.0.0.js:13
m$dzb.print(($dzd=["one","two"].rt$({t:m$dzb.$_String},1),m$dzc.ArrayList$ecti
                                                                ^
TypeError: undefined is not a function
    at run (/Users/jvasileff/Workspace-Ceylon/TesJS/modules/testjs/1.0.0/testjs-1.0.0.js:13:65)
    at [eval]:1:282
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
```

Compiling w/the CLI does work:
```
$ ceylon compile-js && ceylon run-js testjs
Note: Created module testjs/1.0.0
{ one, two }
```

Compiling in Eclipse also works if:
* `import ceylon.test "1.1.1";` is removed, *or*
* "Compile project for JVM" is also enabled

It's important to perform a "Project->Clean" after each change or CLI command.

**Comment by jvasileff** [comment]
Looks like this works now.
