### ISSUE TITLE
lots of NPEs while attempting to navigate

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1356]
Something is broken. @davidfestal?

```ceylon
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.core.model.JDTModule$BinaryPhasedUnits.getPhasedUnitFromRelativePath(JDTModule.java:167)
	at com.redhat.ceylon.eclipse.core.model.JDTModule$BinaryPhasedUnits.getPhasedUnitFromRelativePath(JDTModule.java:1)
	at com.redhat.ceylon.eclipse.core.model.JDTModule.getPhasedUnitFromRelativePath(JDTModule.java:653)
	at com.redhat.ceylon.eclipse.util.Nodes.getReferencedNodeInUnit(Nodes.java:542)
	at com.redhat.ceylon.eclipse.util.Nodes.getReferencedNode(Nodes.java:416)
	at com.redhat.ceylon.eclipse.code.resolve.CeylonHyperlinkDetector.detectHyperlinks(CeylonHyperlinkDetector.java:124)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:289)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:261)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:469)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4042)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by klinger** [comment]
I get an error message in eclipse: "The Ceylon Java backend compilation failed with a throwable: java.lang.NullPointerException"  as Ceylon Backend Error in line 0. 

My Setup: build IDE from sources yesterday, but got this before with 1.1 on linux and windows machine too. It think MY problem here is part of using mixed modules. If I import a 1.1.1 module:

native("jvm") import ceylon.net "1.1.1";

i cannot use any 1.1.0 modules anymore. Is this intended? I always thought the modular system would allow such mixture. Is there a way to get a better error message?

**Comment by davidfestal** [comment]
@klinger : sorry for closing this issue without fixing your problem. It seems it's not the same indeed. Do you think you could open a new issue for your problem ?

**Comment by gavinking** [comment]
Thanks David.
