### ISSUE TITLE
stackoverflow compiling in eclipse

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1358]
With https://github.com/ceylon/ceylon-ide-eclipse/commit/b1e9dd46518773d1f113f306e2d2f154bd574660, `UnitDependencyVisitor` lines 40 & 45. Works fine w/o that commit.

```
!ENTRY org.eclipse.core.jobs 4 2 2015-05-26 12:32:14.801
!MESSAGE An internal error occurred during: "Building workspace".
!STACK 0
java.lang.StackOverflowError
        at com.redhat.ceylon.model.typechecker.model.ProducedReference.getTypeArguments(ProducedReference.java:60)
        at com.redhat.ceylon.model.typechecker.model.ProducedType.getSatisfiedTypes(ProducedType.java:2619)
        at com.redhat.ceylon.eclipse.core.builder.UnitDependencyVisitor.storeDependency(UnitDependencyVisitor.java:41)
        at com.redhat.ceylon.eclipse.core.builder.UnitDependencyVisitor.storeDependency(UnitDependencyVisitor.java:40)
        at com.redhat.ceylon.eclipse.core.builder.UnitDependencyVisitor.storeDependency(UnitDependencyVisitor.java:45)
        at com.redhat.ceylon.eclipse.core.builder.UnitDependencyVisitor.storeDependency(UnitDependencyVisitor.java:40)
```

**Comment by jvasileff** [comment]
This was fixed.
