### ISSUE TITLE
IDE building fails at tests

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#1365]
When running `mvn clean install`, a zillion error messages shows up, like:
```
running: test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta::aliasedTypeRecognized
[ceylon-test] ceylon.test.AssertionComparisonError "assertion failed: expected <Unit[test.ceylon] {
[ceylon-test]   changes = {TopLevelDeclarationAdded ("Integer", invisibleOutside)}
[ceylon-test]   childrenDeltas = {
[ceylon-test]     Method[test] {
[ceylon-test]       changes = {structuralChange}
[ceylon-test]       childrenDeltas = {}
[ceylon-test]     }
[ceylon-test]   }
[ceylon-test] }> but was <Unit[test.ceylon] {
[ceylon-test]   changes = {TopLevelDeclarationAdded ("Integer", invisibleOutside)}
[ceylon-test]   childrenDeltas = {
[ceylon-test]     Function[test] {
[ceylon-test]       changes = {structuralChange}
[ceylon-test]       childrenDeltas = {}
[ceylon-test]     }
[ceylon-test]   }
[ceylon-test] }>"
[ceylon-test] 	at ceylon.test.assertEquals_.assertEquals(assertions.ceylon:98)
[ceylon-test] 	at ceylon.test.assertEquals_.assertEquals(assertions.ceylon:93)
[ceylon-test] 	at test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta.compare_.compare(testUtils.ceylon:150)
[ceylon-test] 	at test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta.compare_.compare(testUtils.ceylon:100)
[ceylon-test] 	at test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta.comparePhasedUnits_.comparePhasedUnits(testUtils.ceylon:183)
[ceylon-test] 	at test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta.aliasedTypeRecognized_.aliasedTypeRecognized(TypedDeclarationStructuralChanges.ceylon:78)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.$call$(AppliedFunction.java:251)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.Util.apply(Util.java:1371)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.apply(Metamodel.java:1643)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:403)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:232)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:221)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.invoke(FreeFunction.java:214)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.invokeFunction$priv$(DefaultTestExecutor.ceylon:228)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.access$100(DefaultTestExecutor.ceylon:20)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor$4.$call$(DefaultTestExecutor.ceylon:196)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor$2.$call$(DefaultTestExecutor.ceylon:163)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor$3.$call$(DefaultTestExecutor.ceylon:170)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor$1.$call$(DefaultTestExecutor.ceylon:146)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.execute(DefaultTestExecutor.ceylon:32)
[ceylon-test] 	at ceylon.test.core.DefaultTestRunner$5$1.next(DefaultTestRunner.ceylon:60)
[ceylon-test] 	at ceylon.language.Array.createArrayFromIterable(Array.java:150)
[ceylon-test] 	at ceylon.language.Array.<init>(Array.java:100)
[ceylon-test] 	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:232)
[ceylon-test] 	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
[ceylon-test] 	at ceylon.test.core.DefaultTestRunner.run(DefaultTestRunner.ceylon:60)
[ceylon-test] 	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:85)
[ceylon-test] 	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:36)
[ceylon-test] 	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ceylon-test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-test] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-test] running: test.com.redhat.ceylon.eclipse.ui.ceylon.model.delta::annotationErrorAdded
[ceylon-test] 	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
[ceylon-test] 	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
[ceylon-test] 	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
[ceylon-test] 	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
[ceylon-test] 	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
[ceylon-test] 	at ceylon.modules.Main.execute(Main.java:69)
[ceylon-test] 	at ceylon.modules.Main.main(Main.java:42)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ceylon-test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-test] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-test] 	at org.jboss.modules.Module.run(Module.java:312)
[ceylon-test] 	at org.jboss.modules.Main.main(Main.java:460)
[ceylon-test] 	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
[ceylon-test] 	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:173)
[ceylon-test] 	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
[ceylon-test] 	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ceylon-test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-test] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-test] 	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
[ceylon-test] 	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
[ceylon-test] 	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-test] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ceylon-test] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-test] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ceylon-test] 	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
[ceylon-test] 	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```
Seems that `Method[test]` has been transmogrified to `Function[test]`.
Well, I'm a bit reluctant to use `-DskipTests`...

**Comment by davidfestal** [comment]
@jpragey : Yes, this change is very recent, and I didn't update the tests for the moment.
Thanks for reporting.

**Comment by davidfestal** [comment]
Fixed now: I've been able to build the IDE through Maven without the `-DskipTests` option.
