### ISSUE TITLE
error rendering stack frame label

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1366]
```
!MESSAGE An internal error occurred during: "Label Job".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.charAt(String.java:646)
	at com.redhat.ceylon.eclipse.util.JavaSearch.getCeylonSimpleName(JavaSearch.java:349)
	at com.redhat.ceylon.eclipse.util.JavaSearch.elementEqualsDeclaration(JavaSearch.java:403)
	at com.redhat.ceylon.eclipse.util.JavaSearch.toCeylonDeclaration(JavaSearch.java:728)
	at com.redhat.ceylon.eclipse.core.debug.DebugUtils.getSourceDeclaration(DebugUtils.java:247)
	at com.redhat.ceylon.eclipse.core.debug.presentation.CeylonStackFrameLabelProvider.updateExistingLabel(CeylonStackFrameLabelProvider.java:38)
	at com.redhat.ceylon.eclipse.core.debug.presentation.CeylonStackFrameLabelProvider.getLabel(CeylonStackFrameLabelProvider.java:75)
	at org.eclipse.debug.internal.ui.model.elements.ElementLabelProvider.getLabel(ElementLabelProvider.java:318)
	at com.redhat.ceylon.eclipse.core.debug.presentation.CeylonStackFrameLabelProvider.getLabel(CeylonStackFrameLabelProvider.java:87)
	at org.eclipse.debug.internal.ui.model.elements.ElementLabelProvider.retrieveLabel(ElementLabelProvider.java:221)
	at org.eclipse.jdt.internal.debug.ui.variables.JavaStackFrameLabelProvider.retrieveLabel(JavaStackFrameLabelProvider.java:41)
	at com.redhat.ceylon.eclipse.core.debug.presentation.CeylonStackFrameLabelProvider.retrieveLabel(CeylonStackFrameLabelProvider.java:26)
	at org.eclipse.debug.internal.ui.model.elements.ElementLabelProvider$LabelUpdater.run(ElementLabelProvider.java:166)
	at org.eclipse.debug.internal.ui.model.elements.ElementLabelProvider$LabelJob.run(ElementLabelProvider.java:75)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

@davidfestal, one for you

**Comment by davidfestal** [comment]
I'm closing it.

**Comment by gavinking** [comment]
Thanks!
