### ISSUE TITLE
Completion proposals retrieved in the UI thread in the `AnnotationInformationControl`

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1402]
In some case, the lookup of completion proposals can be a bit long (several seconds). So if many hovering events are triggered, this lookup is scheduled in the UI thread many times, which finally freezes the UI of Eclipse for a while.
This lookup should be done in a background thread, and the results should be added (inside a UI Thread) only if the information controller had not been dismissed in the meantime. And for performance this background lookup should be canceled  when the current hover is dismissed.

**Comment by gavinking** [comment]
Isn't this what `ProgressMonitor` cancellation is for?

**Comment by davidfestal** [comment]
it is in place when there is no ability to cancel a ProgressMonitor

**Comment by gavinking** [comment]
@davidfestal I don't think that's correct. There _is_ a `ProgressMonitor` in the code where we prepare completion proposals, you just need to find a way to mark it as cancelled.

**Comment by davidfestal** [comment]
`AnnotationInfo.getCompletionProposals()`, `CeylonCorrectionProcess.addProposals()` don't have a `ProgressMonitor`, and the blocking action (of the one that takes the time) is `addChangeReferenceProposals()`

**Comment by davidfestal** [comment]
I'm looking into it to understand why it is blocking this way

**Comment by gavinking** [comment]
@davidfestal this change resulted in the following bug:

```
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.code.refactor.AbstractLinkedMode.<init>(AbstractLinkedMode.java:48)
	at com.redhat.ceylon.eclipse.code.correct.LocalProposal.<init>(LocalProposal.java:230)
	at com.redhat.ceylon.eclipse.code.correct.AssignToLocalProposal.<init>(AssignToLocalProposal.java:46)
	at com.redhat.ceylon.eclipse.code.correct.AssignToLocalProposal.addAssignToLocalProposal(AssignToLocalProposal.java:91)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:691)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:406)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectAnnotationFixes(AnnotationInfo.java:113)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:68)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:227)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
I'll fix it tonight or tomorrow.

**Comment by gavinking** [comment]
Thanks.

**Comment by davidfestal** [comment]
@gavinking : I've fixed the NPE introduced.

In fact it's all related to the fact that we don't explicitly know which part of the code can *only* be called from the UI Thread. It appears that `EditorUtil.getCurrentEditor()` will return `null` if not called from the UI Thread.
So the various places where it is called (such as the `LocalProposal` constructor) cannot be called from a non-UI Thread, which also prevents `CeylonCorrectionProcessor.addProposals()` to be called from a background thread. It's a pity since `CeylonCorrectionProcessor.addProposals()` might take time in some cases, and indeed doesn't require much use of the UI.

It seems to me that, in the design, we should have maintained a more clear line between *UI-thread-only* code and *background-compatible* code. Because of this line being currently nonexistent,  it's very fragile to try pushing some of the *mainly-non-ui* algorithms to background thread, in order to enhance responsiveness. Simply because of implicit UI-only instructions like `getCurrentEditor()` eing called somewhere in a call stack, that implies that all transitive caller of this code is also UI-Thread-only.

IMO this might benefit from some refactoring done specifically in this regard.
