### ISSUE TITLE
NPE "Retrieving Fixes"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1409]
I'm not sure how to troubleshoot this, so the raw data is below. There are a lot of untyped variables since I had just pasted code from elsewhere.

```
!ENTRY org.eclipse.core.jobs 4 2 2015-07-25 18:33:42.452
!MESSAGE An internal error occurred during: "Retrieving Fixes".
!STACK 0
java.lang.NullPointerException
        at com.redhat.ceylon.eclipse.code.correct.ObjectClassDefinitionGenerator.appendRefinementText(ObjectClassDefinitionGenerator.java:272)
        at com.redhat.ceylon.eclipse.code.correct.ObjectClassDefinitionGenerator.appendMembers(ObjectClassDefinitionGenerator.java:232)
        at com.redhat.ceylon.eclipse.code.correct.ObjectClassDefinitionGenerator.generateInternal(ObjectClassDefinitionGenerator.java:159)
        at com.redhat.ceylon.eclipse.code.correct.ObjectClassDefinitionGenerator.generate(ObjectClassDefinitionGenerator.java:106)
        at com.redhat.ceylon.eclipse.code.correct.CreateProposal.addCreateProposal(CreateProposal.java:164)
        at com.redhat.ceylon.eclipse.code.correct.CreateProposal.addCreateLocalProposals(CreateProposal.java:221)
        at com.redhat.ceylon.eclipse.code.correct.CreateProposal.addCreateProposals(CreateProposal.java:282)
        at com.redhat.ceylon.eclipse.code.correct.CreateProposal.addCreateProposals(CreateProposal.java:267)
        at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addCreationProposals(CeylonCorrectionProcessor.java:1311)
        at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:521)
        at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:407)
        at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectAnnotationFixes(AnnotationInfo.java:113)
        at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:68)
        at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:227)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

<img width="651" alt="screen shot 2015-07-25 at 6 34 46 pm" src="https://cloud.githubusercontent.com/assets/236050/8891536/25d5fc4c-32fc-11e5-9ebf-ca6118d1472f.png">

**Comment by davidfestal** [comment]
I have a quite clear idea about this one, and should be able to fix it today.

**Comment by bjansen** [comment]
I think it happens only when the project is building.

**Comment by davidfestal** [comment]
yes, it seems.
