### ISSUE TITLE
Invalid Thread Access during refactoring retrieval

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1432]
```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.SWT.error(SWT.java:4327)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:476)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:414)
	at org.eclipse.swt.widgets.Control.getShell(Control.java:2891)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:737)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:409)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectAnnotationFixes(AnnotationInfo.java:114)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:69)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by davidfestal** [comment]
@gavinking : now the `CeylonCorrectionProcessor.addProposals()` method is also called by non-UI threads (after the fix for #1402). The comment [here](https://github.com/ceylon/ceylon-ide-eclipse/issues/1402#issuecomment-124527485) applies here also it seems.

I'll pass the invocation context instead of the shell object to the `addMoveDirProposal()` function, so that the shell object will be retrieved later, only when needed, during the `MoveDirProposal.apply()` call (which should normally be called in an UI Thread).
