### ISSUE TITLE
Unsupported declaration type: unknown

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1445]
I've been getting a ton of the error below - every time I save a particular file. The project does compile successfully after `Project`->`Clean`.

```
!ENTRY org.eclipse.core.jobs 4 2 2015-08-15 23:00:01.053
!MESSAGE An internal error occurred during: "Building workspace".
!STACK 0
com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported declaration type: unknown
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1684)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1679)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:821)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorsForProducedTypes(Metamodel.java:858)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:780)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForArguments(Metamodel.java:1164)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:548)
        at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:317)
        at ceylon.language.meta.typeLiteral_.typeLiteral(typeLiteral_.java:28)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder$1lookForChanges_.lookForChanges(deltaBuilder.ceylon:685)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder$1$1.$evaluate$(deltaBuilder.ceylon:700)
        at com.redhat.ceylon.compiler.java.language.LazyIterable$LazyIterator.next(LazyIterable.java:41)
        at ceylon.language.any_.any(any.ceylon:10)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder$1.$call$(deltaBuilder.ceylon:697)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder$1.$call$(deltaBuilder.ceylon:691)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder$1lookForChanges_.lookForChanges(deltaBuilder.ceylon:679)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeclarationDeltaBuilder.hasStructuralChanges(deltaBuilder.ceylon:690)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.calculateLocalChanges(deltaBuilder.ceylon:878)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:169)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.buildDelta(deltaBuilder.ceylon:847)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.manageChildDelta(deltaBuilder.ceylon:472)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:218)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.buildDelta(deltaBuilder.ceylon:457)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildCompilationUnitDeltas$priv$(deltaBuilder.ceylon:114)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas$canonical$(deltaBuilder.ceylon:91)
        at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas(deltaBuilder.ceylon:80)
        at com.redhat.ceylon.eclipse.core.model.ProjectSourceFile.buildDeltaAgainstModel(ProjectSourceFile.java:112)
        at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.searchForDependantFiles(CeylonBuilder.java:1460)
        at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.calculateDependencies(CeylonBuilder.java:1317)
        at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:970)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
<img width="715" alt="screen shot 2015-08-15 at 10 59 19 pm" src="https://cloud.githubusercontent.com/assets/236050/9291788/28d63b58-43a2-11e5-834e-37481dff163e.png">

**Comment by jvasileff** [comment]
Appears to be unrelated to the code snippet above; still happened after commenting out recently added code.

Also, no longer reproducible after restarting Eclipse.

**Comment by davidfestal** [comment]
It should not happen anymore. at least not be a blocking problem anymore.
Closing.
