### ISSUE TITLE
API change in Eclipse Neon

### ISSUE THREAD

**Issue by luolong** [ceylon/ceylon-ide-eclipse#1464]
When installing Ceylon on top of recent milestone builds of Eclipse Neon (i.e. _Neon Milestone 1 (4.6.0M1)_), I get lots of errors in the Ceylon IDE.

Eclipse Error log shows error messages with the following stack trace:
```text
java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.env.IBinaryMethod.getParameterAnnotations(I)[Lorg/eclipse/jdt/internal/compiler/env/IBinaryAnnotation;
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader$ModelLoaderTypeRequestor.accept(JDTModelLoader.java:450)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:154)
    at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:100)
    at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:189)
    at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.getMemberType(BinaryTypeBinding.java:1150)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1511)
    at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:762)
    at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:871)
    at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:484)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:710)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.cacheBinaryType(LookupEnvironment.java:228)
    at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.cacheBinaryType(LookupEnvironment.java:215)
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toBinding(JDTModelLoader.java:1132)
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.buildClassMirror(JDTModelLoader.java:1097)
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.lookupNewClassMirror(JDTModelLoader.java:788)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:357)
    at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1436)
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.convertToDeclaration(JDTModelLoader.java:1188)
    at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.loadPackage(JDTModelLoader.java:379)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.fullTypeCheck(CeylonBuilder.java:1976)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.access$100(CeylonBuilder.java:210)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:941)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:937)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:260)
    at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:937)
    […]
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by lucaswerkmeister** [comment]
Looks like this changed in eclipse/objectteams@210dc3aedceebf637dae1d761c2a61d31b823e1f

**Comment by luolong** [comment]
probably this interface change: 

```diff
-public IBinaryAnnotation[] getParameterAnnotations(int index) {
+public IBinaryAnnotation[] getParameterAnnotations(int index, char[] classFileName) {
```

**Comment by simonthum** [comment]
Just had this issue with Neon M7

**Comment by gavinking** [comment]
With the current milestone I get:

```
Errors occurred during the build.
Errors running builder 'Ceylon Builder' on project 'ceylon-sdk'.
org.eclipse.jdt.internal.compiler.env.IBinaryMethod.getParameterAnnotations(I)[Lorg/eclipse/jdt/internal/compiler/env/IBinaryAnnotation;
```

**Comment by lucono** [comment]
> With the current milestone I get:

> ```
Errors occurred during the build.
Errors running builder 'Ceylon Builder' on project 'ceylon-sdk'.
org.eclipse.jdt.internal.compiler.env.IBinaryMethod.getParameterAnnotations(I)[Lorg/eclipse/jdt/internal/compiler/env/IBinaryAnnotation;
```

Same here.

**Comment by JohnWillow** [comment]
FYI: Neon will be released 4 days from now, and "everyone" will start using it.
I plan to upgrade, is this issue fixed?

**Comment by gavinking** [comment]
👏
