### ISSUE TITLE
add module import to module descriptor quick fix does not work from hover

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1468]
@davidfestal here's one more like this! For you.

**Comment by gavinking** [comment]
```
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.code.correct.AddModuleImportProposal.addModuleImportProposals(AddModuleImportProposal.java:142)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:725)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:408)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectAnnotationFixes(AnnotationInfo.java:114)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:69)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by gavinking** [comment]
Fixed.
