### ISSUE TITLE
npe calling delta builder

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1477]
For you @davidfestal 

```
could not resolve dependent unit: source/module2/run.ceylon
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.registerMemberAddedChange(deltaBuilder.ceylon:874)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:221)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$TopLevelDeclarationDeltaBuilder.buildDelta(deltaBuilder.ceylon:862)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.manageChildDelta(deltaBuilder.ceylon:472)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:218)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$RegularCompilationUnitDeltaBuilder.buildDelta(deltaBuilder.ceylon:457)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildCompilationUnitDeltas$priv$(deltaBuilder.ceylon:114)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas$canonical$(deltaBuilder.ceylon:91)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas(deltaBuilder.ceylon:80)
	at com.redhat.ceylon.eclipse.core.model.ProjectSourceFile.buildDeltaAgainstModel(ProjectSourceFile.java:113)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.searchForDependantFiles(CeylonBuilder.java:1461)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.calculateDependencies(CeylonBuilder.java:1318)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:971)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
@gavinking : it's fixed, at least I think so, as for the fact that the name of Declaration can be null.
Can you confirm this fixed your problem ?

**Comment by gavinking** [comment]
Well, since I don't have any particular way I know to reproduce this, let's just close it. Thanks!
