### ISSUE TITLE
Random ConcurrentModificationExceptions

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1485]
I get a fair number of these at various times:

```
!ENTRY org.eclipse.jface 4 2 2015-09-14 16:52:09.092
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.redhat.ceylon.model.typechecker.model.Unit.getImportedDeclaration(Unit.java:148)
        at com.redhat.ceylon.model.typechecker.model.Package.getMemberOrParameter(Package.java:184)
        at com.redhat.ceylon.eclipse.util.SingleSourceUnitPackage.getMemberOrParameter(SingleSourceUnitPackage.java:130)
        at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:118)
        at com.redhat.ceylon.compiler.typechecker.analyzer.AnalyzerUtil.getTypeDeclaration(AnalyzerUtil.java:113)
        at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor$6.initDeclaration(DeclarationVisitor.java:2171)
        at com.redhat.ceylon.model.typechecker.model.LazyType.getDeclaration(LazyType.java:28)
        at com.redhat.ceylon.model.typechecker.model.ClassOrInterface.getSatisfiedTypes(ClassOrInterface.java:105)
        at com.redhat.ceylon.model.typechecker.model.Type.getInternalSatisfiedTypes(Type.java:2661)
        at com.redhat.ceylon.model.typechecker.model.Type.getPrincipalInstantiation(Type.java:1680)
        at com.redhat.ceylon.model.typechecker.model.Type.getSupertype(Type.java:1552)
        at com.redhat.ceylon.model.typechecker.model.TypeDeclaration.getSupertypeDeclaration(TypeDeclaration.java:769)
        at com.redhat.ceylon.model.typechecker.model.TypeDeclaration.getMemberOrParameter(TypeDeclaration.java:579)
        at com.redhat.ceylon.model.typechecker.model.Element.getMemberOrParameter(Element.java:112)
        at com.redhat.ceylon.compiler.typechecker.analyzer.AnalyzerUtil.getTypeDeclaration(AnalyzerUtil.java:113)
        at com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor$6.initDeclaration(DeclarationVisitor.java:2171)
        at com.redhat.ceylon.model.typechecker.model.LazyType.getDeclaration(LazyType.java:28)
        at com.redhat.ceylon.model.typechecker.model.ClassOrInterface.getExtendedType(ClassOrInterface.java:84)
        at com.redhat.ceylon.model.typechecker.model.Class.getExtendedType(Class.java:203)
        at com.redhat.ceylon.eclipse.code.editor.AdditionalAnnotationCreator.getRefinedDeclaration(AdditionalAnnotationCreator.java:145)
        at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getDecorationAttributes(CeylonLabelProvider.java:1319)
        at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getNodeDecorationAttributes(CeylonLabelProvider.java:1232)
        at com.redhat.ceylon.eclipse.code.outline.CeylonOutlineNode.getDecorations(CeylonOutlineNode.java:313)
        at com.redhat.ceylon.eclipse.code.outline.CeylonOutlineLabelProvider.getImage(CeylonOutlineLabelProvider.java:79)
        at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:195)
        at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:173)
        at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:121)
        at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:136)
        at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:154)
        at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:949)
        at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:114)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1029)
        at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:473)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2176)
        at org.eclipse.jface.viewers.StructuredViewer.internalUpdate(StructuredViewer.java:2159)
        at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2097)
        at org.eclipse.jface.viewers.ColumnViewer.update(ColumnViewer.java:541)
        at org.eclipse.jface.viewers.StructuredViewer.update(StructuredViewer.java:2041)
        at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1208)
        at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:99)
        at org.eclipse.jface.viewers.BaseLabelProvider$1.run(BaseLabelProvider.java:72)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.BaseLabelProvider.fireLabelProviderChanged(BaseLabelProvider.java:69)
        at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider$1.labelProviderChanged(DecoratingStyledCellLabelProvider.java:78)
        at org.eclipse.ui.internal.decorators.DecoratorManager$1.run(DecoratorManager.java:446)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.decorators.DecoratorManager.fireListener(DecoratorManager.java:443)
        at org.eclipse.ui.internal.decorators.DecorationScheduler$3.runInUIThread(DecorationScheduler.java:536)
        at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by davidfestal** [comment]
it should be fixed now.
please @jvasileff could you confirm this is fixed also for you, and, if not, reopen the issue ?

**Comment by jvasileff** [comment]
Great, thanks @davidfestal! I'll let you know if I see it again.
