### ISSUE TITLE
NPE for Ceylon project with no backend

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1511]
@davidfestal please fix this:

```
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.core.external.ExternalSourceArchiveManager.updateProjectSourceArchives(ExternalSourceArchiveManager.java:624)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2362)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2132)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:265)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2132)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2129)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:316)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2129)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonProjectModulesContainer.resolveClasspath(CeylonProjectModulesContainer.java:312)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:902)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
See @30aafbe.

**Comment by gavinking** [comment]
Fixed, I think.
