### ISSUE TITLE
shared unit test Run As > Ceylon Test Java Script does nothing

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1519]
1) Create an Eclipse project that supports Java and JavaScript
2) Write a very simple unit test

```ceylon
import ceylon.test {
    assertTrue,
    test
}

test
shared void testMe() {
    assertTrue(true);
}
```
3) Click on either the Ceylon file or the package folder.
4) Run As > Ceylon Test  (will succeed in showing results in the Ceylon Test View)
5) Run As > Ceylon Test JavaScript

Fails to show anything in the Ceylon Test View

Only outputs this at the console:

```
NODE_PATH=${ECLIPSE_HOME}/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151005-1936/repo:${WORKSPACE_HOME}/JavaAndJavaScript/modules:${HOME}/.ceylon/repo:${HOME}/.ceylon/cache:[Maven] Aether:${WORKSPACE_HOME}/JavaAndJavaScript/modules
```

**Comment by FroMage** [comment]
Yes I experience that as well, @thradec could you take a look please?

**Comment by thradec** [comment]
I have this log in console (from IDE and CLI) ...

```
/Users/thradec/.ceylon/repo/com/redhat/ceylon/test/1.1.1/com.redhat.ceylon.test-1.1.1.js:12
ex$.$pkgunsh$com$redhat$ceylon$test={'htmlEntitiesMap':$prop$getHtmlEntitiesMa
                                                       ^
ReferenceError: $prop$getHtmlEntitiesMap is not defined
    at /Users/thradec/.ceylon/repo/com/redhat/ceylon/test/1.1.1/com.redhat.ceylon.test-1.1.1.js:12:56
    at /Users/thradec/.ceylon/repo/com/redhat/ceylon/test/1.1.1/com.redhat.ceylon.test-1.1.1.js:15:37
    at /Users/thradec/.ceylon/repo/com/redhat/ceylon/test/1.1.1/com.redhat.ceylon.test-1.1.1.js:1:83
    at Object.<anonymous> (/Users/thradec/.ceylon/repo/com/redhat/ceylon/test/1.1.1/com.redhat.ceylon.test-1.1.1.js:14:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
ceylon test-js: Node process exited with non-zero exit code: 8
```
... so I would suspect something in js compiler @chochos ?

**Comment by FroMage** [comment]
I don't have that. I suspect you're missing something to recompile…

**Comment by FroMage** [comment]
Actually now it runs both shared and unshared, I can see the output:

```
NODE_PATH=/home/stephane/no-backup/src/eclipse-mars/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151009-1416/repo:/home/stephane/src/java-eclipse/ceylon-sdk/modules:/home/stephane/src/java-eclipse/ceylon-sdk/test-deps:/home/stephane/.ceylon/repo:/home/stephane/.ceylon/cache:[Maven] Aether:/home/stephane/src/java-eclipse/ceylon-sdk/modules
{ f->[foo], b->[bar], l->[last, list], e->[end] }
```

And the Console says "Terminated", but the test does not show up in the test view, although I have "Interrupted: testStef → JavaScript (JS)" on top.

**Comment by chochos** [comment]
this happens only in the IDE? I run all the SDK tests and don't get any errors at all

**Comment by FroMage** [comment]
Well, yes IDE. No error in the tests this time, it's just the Test View that fails to show things.

**Comment by chochos** [comment]
And how is a JS process supposed to tell Eclipse it's done, or notify progress?

**Comment by chochos** [comment]
in any case that's a separate bug, no?

**Comment by FroMage** [comment]
Which separate bug? I can't reproduce @thradec's bug but I can reproduce the original issue.

**Comment by chochos** [comment]
oh, right, I got mixed up.

**Comment by thradec** [comment]
the previous error, which I saw, disappeared after full rebuild, after some debugging it seems, that socket communication between eclipse and test tool stopped working, but I can't see why

**Comment by thradec** [comment]
hopefully fixed for now (via ceylon/ceylon-sdk@14051435711642bedaf352df6f84ef93976cbd75)

**Comment by lukedegruchy** [comment]
Does not work for me.  Running a simple shared unit test as JavaScript seems to hang forever.   The red button in the Console View does not disappear.

**Comment by thradec** [comment]
Sorry, I can't reproduce. Could somebody else try it?

**Comment by jvasileff** [comment]
Is this the same as #1528? I think my comment https://github.com/ceylon/ceylon-ide-eclipse/issues/1528#issuecomment-147216819 applies here too.

**Comment by lukedegruchy** [comment]
The below may be related to https://github.com/ceylon/ceylon-js/issues/643, I'm not sure:

Just rebuilt the distribution and IDE recently:

Depending on the project I'm running JavaScript unit tests either work as expected or I get the following errors:

1) Command line:
```
NODE_PATH=${GITHUB_HOME}/ceylon-dist/dist/repo:/Users/luke/Development/ceylon/github/lukedegruchy/ceylon-chayote/modules:/Users/luke/.ceylon/repo:/Users/luke/.ceylon/cache:[Maven] Aether:/Users/luke/Development/ceylon/github/lukedegruchy/ceylon-chayote/modules
${GITHUB_HOME}/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:637
initExistingTypeProto($JsCallable, Function, 'ceylon.language::JsCallable', Callable);
                                                                            ^

ReferenceError: Callable is not defined
    at ${GITHUB_HOME}/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:637:77
    at ${GITHUB_HOME}/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:5597:37
    at ${GITHUB_HOME}/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1:83
    at Object.<anonymous> (${GITHUB_HOME}/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:5596:2)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
ceylon test-js: Node process exited with non-zero exit code: 1
```


2) Eclipse:
```

NODE_PATH=${ECLIPSE_HOME}/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151011-1228/repo:${LUKE_HOME}/Development/ceylon/github/lukedegruchy/ceylon-chayote/modules:${LUKE_HOME}/.ceylon/repo:${LUKE_HOME}/.ceylon/cache:[Maven] Aether:${LUKE_HOME}/Development/ceylon/github/lukedegruchy/ceylon-chayote/modules
${ECLIPSE_HOME}/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151011-1228/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:263
if (!cond)throw wrapexc(AssertionError(msg),loc,file);
          ^

Error: Assertion failed: 'exists m = modules.find(moduleNameAndVersion[0], moduleNameAndVersion[1])' at tool.ceylon (93:15-93:89)
    at AssertionError (${ECLIPSE_HOME}/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151011-1228/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3617:6)
    at Object.asrt$ (${ECLIPSE_HOME}/Eclipse.app/Contents/Eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20151011-1228/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:263:25)
    at run (${LUKE_HOME}/.ceylon/repo/com/redhat/ceylon/testjs/1.1.1/com.redhat.ceylon.testjs-1.1.1.js:173:5)
    at [eval]:1:336
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:566:27
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
ceylon test-js: Node process exited with non-zero exit code: 1
```

**Comment by FroMage** [comment]
Right, I get the same error, even from the CLI. Files as https://github.com/ceylon/ceylon-js/issues/644

**Comment by FroMage** [comment]
OK, now that the `Callable` error is fixed, I can run JS tests in the IDE. Thanks @thradec !

**Comment by lukedegruchy** [comment]
My previous comment refers to https://github.com/ceylon/ceylon-js/issues/643.
