### ISSUE TITLE
eGit diff fails and SWT exception with latest Ceylon IDE

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon-ide-eclipse#1525]
Not sure if this is a showstopper for 1.2.

This was working on the Ceylon IDE I built recently before.

1) Sync from the github projects and rebuild ceylon-ide-eclipse and update Eclipse
2) Import a Ceylon github project you have commit rights to (this will probably work for a forked project)
3) Make a change to a Ceylon file.
4) Open the Git Staging View
5) Double-click the Ceylon file to show the diff

The diff window will be blank even if there are changes running git diff from the command line.

Here's what I see in the Error Log view (the caused by NullPointerException starts with com.redhat.ceylon.eclipse.core.model.JDTModuleManager.getSupportedBackends):

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.core.model.JDTModuleManager.getSupportedBackends(JDTModuleManager.java:342)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.<init>(PhasedUnit.java:118)
	at com.redhat.ceylon.eclipse.core.typechecker.IdePhasedUnit.<init>(IdePhasedUnit.java:30)
	at com.redhat.ceylon.eclipse.core.typechecker.ModifiablePhasedUnit.<init>(ModifiablePhasedUnit.java:29)
	at com.redhat.ceylon.eclipse.core.typechecker.EditedPhasedUnit.<init>(EditedPhasedUnit.java:29)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.typecheck(CeylonParseController.java:299)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.access$500(CeylonParseController.java:97)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$7.call(CeylonParseController.java:805)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$7.call(CeylonParseController.java:777)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:309)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.parseAndTypecheck(CeylonParseController.java:777)
	at com.redhat.ceylon.eclipse.code.outline.CeylonStructureCreator.createStructureComparator(CeylonStructureCreator.java:90)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.getStructure(StructureCreator.java:81)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.internalCreateStructure(StructureCreator.java:130)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.access$0(StructureCreator.java:109)
	at org.eclipse.compare.structuremergeviewer.StructureCreator$1.run(StructureCreator.java:96)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.internal.Utilities.runInUIThread(Utilities.java:859)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.createStructure(StructureCreator.java:102)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.createStructure(StructureDiffViewer.java:155)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.refresh(StructureDiffViewer.java:133)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.setInput(StructureDiffViewer.java:104)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:347)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$2.run(StructureDiffViewer.java:74)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$6.run(StructureDiffViewer.java:322)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:319)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:307)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.inputChanged(StructureDiffViewer.java:278)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:292)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1701)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:277)
	at org.eclipse.compare.internal.CompareStructureViewerSwitchingPane.setInput(CompareStructureViewerSwitchingPane.java:132)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:747)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:555)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:462)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:422)
	at org.eclipse.compare.internal.CompareEditor$3.run(CompareEditor.java:378)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 23 more
```

**Comment by quintesse** [comment]
This is something I added a couple of days ago (see https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModuleManager.java#L342). I'm guessing it's because `javaProject` can be `null`? @davidfestal ? Could you perhaps fix this? (I might just put a simple null test around it and returns an empty Set, but I currently can't test any of this)

**Comment by lukedegruchy** [comment]
The following change on my local copy of JDKModuleManager.java fixed the issue.   I haven't yet set up a fork of ceylon-ide-eclipse yet, otherwise I'd have done a pull request:

```diff
diff --git a/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModuleManager.java b/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModuleManager.java
index 8408691..e08cef6 100644
--- a/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModuleManager.java
+++ b/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/core/model/JDTModuleManager.java
@@ -339,12 +339,14 @@ public class JDTModuleManager extends LazyModuleManager {
         // TODO At some point we'll need an actual module manager for the
         // JS backend and an IDE that can somehow merge the two when needed
         Set<String> backends = new HashSet<String>();
-        if (CeylonBuilder.compileToJava(javaProject.getProject())) {
-            backends.add(Backend.Java.nativeAnnotation);
-        }
-        if (CeylonBuilder.compileToJs(javaProject.getProject())) {
-            backends.add(Backend.JavaScript.nativeAnnotation);
-        }
+               if (javaProject != null) {
+                       if (CeylonBuilder.compileToJava(javaProject.getProject())) {
+                               backends.add(Backend.Java.nativeAnnotation);
+                       }
+                       if (CeylonBuilder.compileToJs(javaProject.getProject())) {
+                               backends.add(Backend.JavaScript.nativeAnnotation);
+                       }
+               }
         return backends;
     }
 }
```

**Comment by lukedegruchy** [comment]
This is now working for me.

**Comment by gavinking** [comment]
Close it?
