### ISSUE TITLE
NPE when creating new ceylon project

### ISSUE THREAD

**Issue by squilliam-fancypants** [ceylon/ceylon-ide-eclipse#1559]
Using Mars plus development plugin. Do file->new->project...->ceylon->ceylon project.

Get the following stack trace:

Exception:java.lang.NullPointerException: null
	 at com.redhat.ceylon.common.config.ConfigParser.<init>(ConfigParser.java:27)
	 at com.redhat.ceylon.common.config.ConfigFinder.loadConfigFromFile(ConfigFinder.java:257)
	 at com.redhat.ceylon.common.config.ConfigFinder.loadSystemConfig(ConfigFinder.java:158)
	 at com.redhat.ceylon.common.config.ConfigFinder.loadDefaultConfig(ConfigFinder.java:76)
	 at com.redhat.ceylon.common.config.CeylonConfigFinder.loadDefaultConfig(CeylonConfigFinder.java:12)
	 at com.redhat.ceylon.eclipse.code.preferences.CeylonRepoConfigBlock.performDefaults(CeylonRepoConfigBlock.java:109)
	 at com.redhat.ceylon.eclipse.code.preferences.CeylonRepoConfigBlock.initContents(CeylonRepoConfigBlock.java:190)
	 at com.redhat.ceylon.eclipse.code.wizard.NewCeylonProjectWizardPageThree.createControl(NewCeylonProjectWizardPageThree.java:46)
	 at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:175)
	 at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:705)
	 at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1153)
	 at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1211)
	 at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1208)
	 at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1197)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	 at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1194)
	 at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:885)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:425)
	 at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	 at org.eclipse.jface.window.Window.open(Window.java:803)
	 at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:269)
	 at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:290)
	 at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	 at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:497)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	 at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	 at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	 at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	 at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:160)
	 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	 at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	 at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:497)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by davidfestal** [comment]
In the following method of `.../common/FileUtil` : 
```
    /**
     * The OS-specific directory where global application data can be stored.
     * As given by the {@code ceylon.config.dir} system property or the default
     * OS-dependent directory if the property doesn't exist. (/etc/ceylon on
     * Unix-like systems and %ALLUSERSPROFILE%/ceylon on Windows)
     */
    public static File getSystemConfigDir() {
        File configDir = null;
        String ceylonConfigDir = System.getProperty(Constants.PROP_CEYLON_CONFIG_DIR);
        if (ceylonConfigDir != null) {
            configDir = new File(ceylonConfigDir);
        } else {
            if (OSUtil.isWindows()) {
                String appDir = System.getenv("ALLUSERSPROFILE");
                if (appDir != null) {
                    configDir = new File(appDir, "ceylon");
                }
            } else if (OSUtil.isMac()) {
                configDir = new File("/etc/ceylon");
            } else {
                // Assume a "regular" unix OS
                configDir = new File("/etc/ceylon");
            }
        }
        return configDir;
    }
```

we should return a default value for the case when the OS is Windows and the `ALLUSERSPROFILE` environment variable is not set.

@quintesse : any idea to fix this ? Should I reassign it to you ?

**Comment by davidfestal** [comment]
let me do it :-)

**Comment by quintesse** [comment]
You can do it as long as the solution is turning:

```ceylon
    public CeylonConfig loadSystemConfig() throws IOException {
        File configFile = findSystemConfig();
        return loadConfigFromFile(configFile);
    }
```

into:

```ceylon
    public CeylonConfig loadSystemConfig() throws IOException {
        File configFile = findSystemConfig();
        if (configFIle != null) {
            return loadConfigFromFile(configFile);
        } else {
            return new CeylonConfig():
        }
    }
```

;)

**Comment by davidfestal** [comment]
I was meaning : let me reassign it to you :-D

**Comment by quintesse** [comment]
No, you do it, I don't have time to test it right now :)

**Comment by quintesse** [comment]
Also because this is a necessary fix, but we also have to fix the reason why `null` was returned from `getSystemConfigDir()` when running under Cygwin. De we know already?

**Comment by davidfestal** [comment]
of course we know.

**Comment by quintesse** [comment]
Well, why? ;)

**Comment by davidfestal** [comment]
because `OSUtil.isWindow()`  returns `true`.
but visibly the `appDir` is `null`

**Comment by davidfestal** [comment]
we just should return a default value for Windows when not finding the appDir.
at least this wouldn't throw an NPE.

**Comment by quintesse** [comment]
No,that's exactly what I don't want because it would be wrong ;)

**Comment by quintesse** [comment]
We have to handle the fact that `getSystemConfigDir()` can return `null`

**Comment by davidfestal** [comment]
OK I see

**Comment by quintesse** [comment]
**But** at the same time it *should* be able to return the correct value for Cygwin, I just can't believe that Cygwin messes with the Environment variables

**Comment by davidfestal** [comment]
I don't have much time to work on this either (still several pending issues + problems locally with my EclipseMars install, as well as with IncrementalBuildTests that fails)

**Comment by quintesse** [comment]
@squilliam-fancypants could you open a Cygwin shell for us, type `set`, and copy & paste the result here? That way I can try to figure out what's wrong.

**Comment by quintesse** [comment]
Ok, I at least pushed the change for `loadSystemConfig()` which should fix the NPE.

**Comment by squilliam-fancypants** [comment]
Yes. Not in office right now but will within the hour. I am suspecting
something screwy with my ENV variables too.

**Comment by squilliam-fancypants** [comment]
Here is output of set:

ANT_HOME=/cygdrive/c/dev/bin/apache-ant-1.7.1
ANT_OPTS='-Xmx1024m -Xms512m'
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:expand_aliases:extquote:force_fignore:histappend:hostcomplete:interactive_comments:login_shell:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="3" [2]="39" [3]="2" [4]="release" [5]="x86_64-unknown-cygwin")
BASH_VERSION='4.3.39(2)-release'
CATALINA_HOME=/home/sgriese/development/java_projects/apache-tomcat-8.0.24/
COLUMNS=167
CYG_SYS_BASHRC=1
DIRSTACK=()
ECLIPSE_JVM=/cygdrive/c/progra~1/Java/jdk1.7.0_75
EUID=13021
EXECIGNORE='*.dll'
FLEX_HOME=C:/dev/bin/flex-sdk-4.5.1
GROUPS=()
HISTCONTROL=ignoredups
HISTFILE=/home/sgriese/.bash_history
HISTFILESIZE=10000
HISTSIZE=10000
HOME=/home/sgriese
HOSTNAME=sgriese9470
HOSTTYPE=x86_64
IFS=$' \t\n'
INFOPATH=/usr/local/info:/usr/share/info:/usr/info
JAVA_HOME=/cygdrive/c/progra~1/Java/jdk1.8.0_60
JAVA_HOME_6=/cygdrive/c/progra~1/Java/jdk1.6.0_45
JAVA_HOME_7=/cygdrive/c/progra~1/Java/jdk1.7.0_75
JAVA_HOME_8=/cygdrive/c/progra~1/Java/jdk1.8.0_60
JRE_HOME=/cygdrive/c/progra~1/Java/jdk1.8.0_60
LANG=en_US.UTF-8
LINES=71
M2=/cygdrive/c/dev/bin/apache-maven-3.2.5/bin
M2_HOME=/cygdrive/c/dev/bin/apache-maven-3.2.5
MACHTYPE=x86_64-unknown-cygwin
MAILCHECK=60
MAVEN_OPTS=-Xmx1024m
NOVERTEX=true
OLDPWD=/home/sgriese
OPTERR=1
OPTIND=1
ORACLE_HOME_11=/cygdrive/c/oracle/product/11.2.0/dbhome_1
ORACLE_HOME_12=/cygdrive/c/oracle12c/product/12.1.0/dbhome_1
ORACLE_VERSION=11
ORA_HOME=/cygdrive/c/oracle/product/11.2.0/dbhome_1
ORIGINAL_PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
OSTYPE=cygwin
PATH=$'/home/sgriese/development/java_projects/bin:/home/sgriese/development/java_projects/eclipse:/cygdrive/c/progra~1/Java/jdk1.8.0_60/bin:/cygdrive/c/dev/bin/apache-maven-3.2.5/bin:/cygdrive/c/dev/bin/apache-ant-1.7.1/bin:/home/sgriese/development/java_projects/apache-tomcat-8.0.24//bin:/cygdrive/c/oracle/product/11.2.0/dbhome_1/bin:/home/sgriese/bin:/usr/local/bin:/usr/bin:/usr/gnu/bin:/bin\r'
PIPESTATUS=([0]="0")
PPID=13008
PRINTER='\\berps0005\1001-213M'
PROFILEREAD=true
PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
PS2='> '
PS4='+ '
PWD=/home/sgriese/development/java_projects
SHELL=/bin/bash
SHELLOPTS=braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
SHLVL=1
SYSTEMDRIVE=C:
SYSTEMROOT='C:\Windows'
TEMP=/tmp
TERM=cygwin
TMP=/tmp
TZ=America/New_York
UID=13021
USER=sgriese
USE_MIN_ORACLE_VERSION=true
WINDIR='C:\Windows'
_=/tmp
profile_d () 
{ 
    _LC_ALL_SET_="${LC_ALL+set}";
    _LC_SAVE_="${LC_ALL-null}";
    LC_ALL=C;
    if [ "${_LC_SAVE_}" = "null" ]; then
        for file in /etc/profile.d/*.$1;
        do
            [ -e "${file}" ] && . "${file}";
        done;
        unset LC_ALL;
    else
        for file in /etc/profile.d/*.$1;
        do
            [ -e "${file}" ] && LC_ALL="${_LC_SAVE_}" . "${file}";
        done;
        LC_ALL="${_LC_SAVE_}";
    fi;
    unset file;
    unset _LC_ALL_SET_;
    unset _LC_SAVE_
}

**Comment by quintesse** [comment]
Ok, even weirder, would Cygwin actually remove variables from the Windows environment?
Could you paste the output of Window's own `set` command as well @squilliam-fancypants ? Just ot make sure the variables even exist.
And what Windows version are you running?

**Comment by squilliam-fancypants** [comment]
I'm running windows 7 enterprise. Service Pack 1.

Cygwin is likely removing ENV var from original due to me using an exec. It's a long story, but my typical work environment is cluttered with functions and aliases. In order to get a "clean" environment, I run an exec with a specific ENV var that causes this setup to be bypassed in my .bash_profile (the standard work profile).  This is clearly not a good solution, as the exec is not establishing mandatory ENV vars. 

This is my exec:
exec env -i NOVERTEX=true TEMP=$HOME/tmp HOME=$HOME TERM=$TERM SYSTEMDRIVE=$SYSTEMDRIVE SYSTEMROOT=$SYSTEMROOT PS1='\u:\w\$ ' /bin/bash --login

The 'NOVERTEX' is the flag I pass in to branch on in my .bash_profile

**Comment by squilliam-fancypants** [comment]
I apologize for my stupidity causing everyone to scramble for a solution to a problem that probably doesn't exist for anyone else but me.

**Comment by squilliam-fancypants** [comment]
Here is the set run from a windows command line:

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sgriese\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SGRIESE9470
ComSpec=C:\Windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
FP_NO_HOST_CHECK=NO
GOROOT=C:\Go\
HOMEDRIVE=F:
HOMEPATH=\
HOMESHARE=\\berfs0008\users\sgriese
LOCALAPPDATA=C:\Users\sgriese\AppData\Local
LOGONSERVER=\\BERDC0005
MOZ_PLUGIN_PATH=C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\
NUMBER_OF_PROCESSORS=4
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\oracle12c\product\12.1.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\nodejs\;C:\Ruby193\bin;C:\Tcl\bin;C:\ProgramData\Oracle\Java\javapath;C:\oracle12c\product\12.1.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\nodejs\;C:\Users\sgriese\AppData\Roaming\npm;C:\Users\sgriese\AppData\Local\Pandoc\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
PATHGONE=C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\TortoiseSVN\bin;C:\Go\bin
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3a09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SJG=%SystemDrive%
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\sgriese\AppData\Local\Temp
TMP=C:\Users\sgriese\AppData\Local\Temp
ULTRAMON_LANGDIR=C:\Program Files\UltraMon\Resources\en
USERDNSDOMAIN=VERTEXINC.COM
USERDOMAIN=VERTEXINC
USERNAME=sgriese
USERPROFILE=C:\Users\sgriese
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VSEDEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

**Comment by quintesse** [comment]
Ah yes, this is the one we're looking for: `ALLUSERSPROFILE=C:\ProgramData` , you can solve your problem by adding that one your environment :)

**Comment by squilliam-fancypants** [comment]
Thank you. I'm actually going back and coming up with a way to have a "non-work" environment without using the sledgehammer 'exec' approach. But thanks for pointing out the relevant ENV var. And sorry for the bother.

**Comment by quintesse** [comment]
ok, then together with my fix for the NPE, we can consider this closed. Don't worry @squilliam-fancypants you *did* find an actual bug :)

**Comment by squilliam-fancypants** [comment]
Oh, okay. Well that's good, I guess. Thanks! :)
