### ISSUE TITLE
CCE in Eclipse log

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1562]
Suddenly I see some of these:

```
java.lang.ClassCastException: com.redhat.ceylon.eclipse.core.model.mirror.UnknownTypeMirror cannot be cast to java.lang.String
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getAnnotationStringValue(AbstractModelLoader.java:1930)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:1843)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.loadCompiledModule(AbstractModelLoader.java:1835)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:125)
	at com.redhat.ceylon.eclipse.core.model.JDTModuleSourceMapper.resolveModule(JDTModuleSourceMapper.java:120)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:265)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$400(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:112)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:48)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:73)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:96)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2319)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2141)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:269)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2141)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2138)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:320)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2138)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonProjectModulesContainer.resolveClasspath(CeylonProjectModulesContainer.java:311)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:906)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by quintesse** [comment]
Perhaps this is because of https://github.com/ceylon/ceylon-model/commit/91216dbc76f708f116ae763ba653a7e1a6f17ae6 ?

**Comment by davidfestal** [comment]
@gavinking : After pulling and rebuilding everything and installing in my main Eclipse, I don't experiment this all. Can we close it ?

**Comment by gavinking** [comment]
OK, I don't see it anymore either.
