### ISSUE TITLE
error compiling SDK in latest Eclipse

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1608]
I get:

```
The ImportVisitor caused an exception visiting a Import node: "java.lang.NullPointerException" at org.eclipse.objectteams.otdt.internal.core.compiler.control.Config.getBundledCompleteTypeBindingsMode(Config.java:461)
```

And

```
!ENTRY org.eclipse.jdt.core 2 0 2015-11-12 23:02:42.524
!MESSAGE Processing CU /ceylon-sdk/source/ceylon/net/http/server/internal/JavaHelper.java failed
!STACK 0
org.eclipse.objectteams.otdt.internal.core.compiler.control.Config$NotConfiguredException: LookupEnvironment not configured
	at org.eclipse.objectteams.otdt.internal.core.compiler.control.Config.getLookupEnvironment(Config.java:344)
	at org.eclipse.objectteams.otdt.internal.core.compiler.control.Dependencies.establishUnitState(Dependencies.java:300)
	at org.eclipse.objectteams.otdt.internal.core.compiler.control.Dependencies.ensureState(Dependencies.java:263)
	at org.eclipse.objectteams.otdt.internal.core.compiler.control.Dependencies.ensureState(Dependencies.java:255)
	at org.eclipse.objectteams.otdt.internal.core.compiler.control.Dependencies.ensureState(Dependencies.java:255)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:287)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader$ModelLoaderTypeRequestor.accept(JDTModelLoader.java:493)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader$ModelLoaderTypeRequestor.accept(JDTModelLoader.java:429)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:274)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1457)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toBinding(JDTModelLoader.java:1276)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.buildClassMirror(JDTModelLoader.java:1225)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.lookupNewClassMirror(JDTModelLoader.java:880)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.lookupClassMirror(AbstractModelLoader.java:372)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMemberMemoised(LazyPackage.java:99)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getDirectMember(LazyPackage.java:66)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMember(LazyPackage.java:49)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ImportVisitor.importMember(ImportVisitor.java:291)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ImportVisitor.visit(ImportVisitor.java:85)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Import.visit(Tree.java:238)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkImportList(Walker.java:78)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ImportList.visitChildren(Tree.java:218)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:17)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ImportList.visit(Tree.java:210)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:16)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ImportVisitor.visit(ImportVisitor.java:58)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.scanTypeDeclarations(PhasedUnit.java:380)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$2.run(CeylonParseController.java:307)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$3.run(CeylonParseController.java:332)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
Apparently this was caused by the stupid ObjectTeams patch the Eclipse pushed on me.

**Comment by davidfestal** [comment]
@gavinking: so can we close this one ?

**Comment by davidfestal** [comment]
let me close it then, and please @gavinking reopen it if you want
