### ISSUE TITLE
autocompletion broken for modules imported from maven

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1620]
I have a project which imports Hibernate from maven and I can't autocomplete members of `EntityManager`, among many other completion-related problems.

**Comment by gavinking** [comment]
For reference:

```ceylon
native("jvm")
module hib "1.0.0" {
    import "org.hibernate:hibernate-entitymanager" "5.0.4.Final";
    import "org.hsqldb:hsqldb" "2.3.1";
}
```

```xml
<overrides xmlns="http://www.ceylon-lang.org/xsd/overrides">
    <module groupId="org.hibernate" 
         artifactId="hibernate-entitymanager">
        <share groupId="org.hibernate" 
            artifactId="hibernate-core"/>
        <share groupId="org.javassist" 
            artifactId="javassist"/>
        <share groupId="org.hibernate.javax.persistence" 
            artifactId="hibernate-jpa-2.1-api"/>
    </module>
	<module groupId="org.hibernate" 
	     artifactId="hibernate-core">
		<add groupId="javax.transaction" 
		  artifactId="jta" 
		     version="1.1"
		      shared="true"/>
	</module>
</overrides>
```

**Comment by bjansen** [comment]
```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:420)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2156)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2152)
	at com.redhat.ceylon.eclipse.code.complete.EclipseCompletionManager.computeCompletionProposals(eclipseCompletionManager.ceylon:154)
	at org.eclipse.jface.text.contentassist.ContentAssistant$5.run(ContentAssistant.java:1904)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1902)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:499)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1720)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:967)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1501)
	at com.redhat.ceylon.eclipse.code.editor.CeylonSourceViewer.doOperation(CeylonSourceViewer.java:249)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1105)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4225)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1528)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:496)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1060)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5784)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:68)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:594)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5694)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2130)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2337)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5756)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5193)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5342)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3695)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: com.redhat.ceylon.model.loader.ModelResolutionException: JDT reference binding without a JDT IType element : javax.persistence.EntityGraph
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.toType(JDTModelLoader.java:1148)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.<init>(JDTType.java:201)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTType.<init>(JDTType.java:113)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod$2.doWithBinding(JDTMethod.java:201)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.doWithMethodBinding(JDTModelLoader.java:1055)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod.doWithBindings(JDTMethod.java:292)
	at com.redhat.ceylon.eclipse.core.model.mirror.JDTMethod.getParameters(JDTMethod.java:151)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setParameters(AbstractModelLoader.java:3729)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addMethod(AbstractModelLoader.java:3138)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2594)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2098)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:97)
	at com.redhat.ceylon.model.loader.model.LazyClass.getParameterLists(LazyClass.java:172)
	at com.redhat.ceylon.ide.common.completion.InvocationCompletion$impl.addInvocationProposals(InvocationCompletion.ceylon:222)
	at com.redhat.ceylon.ide.common.completion.IdeCompletionManager.addInvocationProposals(IdeCompletionManager.ceylon)
	at com.redhat.ceylon.ide.common.completion.IdeCompletionManager.constructCompletions(IdeCompletionManager.ceylon:814)
	at com.redhat.ceylon.ide.common.completion.IdeCompletionManager.getContentProposals$canonical$(IdeCompletionManager.ceylon:237)
	at com.redhat.ceylon.ide.common.completion.IdeCompletionManager.getContentProposals(IdeCompletionManager.ceylon:109)
	at com.redhat.ceylon.eclipse.code.complete.EclipseCompletionManager.getEclipseContentProposals$priv$(eclipseCompletionManager.ceylon:384)
	at com.redhat.ceylon.eclipse.code.complete.EclipseCompletionManager.access$300(eclipseCompletionManager.ceylon:100)
	at com.redhat.ceylon.eclipse.code.complete.EclipseCompletionManager$1Runnable.run(eclipseCompletionManager.ceylon:140)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

Brrr, too scary for me!

**Comment by davidfestal** [comment]
@gavinking, @bjansen: strange, with exactly your project and the following run function:
```ceylon
import javax.persistence {
	EntityManager
}
"Run the module `hib`."
shared void run() {
	EntityManager em = nothing;
	em.clear();
}
```
I can auto-complete the members of `em` without any problem.

Is there some use case I missed to be able to reproduce the error ?

**Comment by bjansen** [comment]
Can you autocomplete `EntityManager` when it's not imported?

**Comment by davidfestal** [comment]
In fact to write this code, I didn't enter the import manually. Just typed `Entity`, and the auto-completion proposed `EntityManager` and then added the import.

**Comment by davidfestal** [comment]
didn't see anything not working as normal here.

**Comment by bjansen** [comment]
I can still see the same error on a fresh build when I run Eclipse from Eclipse.

**Comment by davidfestal** [comment]
strange

**Comment by bjansen** [comment]
Oops sorry, I forgot the `overrides.xml`, everything seems to work fine (even in my main Eclipse instance).

**Comment by bjansen** [comment]
@gavinking I don't see any particular problem here, could you test with a fresh build and let me know if you still have problems?

**Comment by gavinking** [comment]
Guys I just retested with a brand new project, and I still get the same broken behavior.

**Comment by gavinking** [comment]
Oh fuckety fuck fuck fuck not again.

I am a fucking moron.

*Again* I'm wasting you guys' time because I'm incapable of remembering that I have filters set up.

For fucks sake.

Sorry.

**Comment by quintesse** [comment]
One option is that you're a moron , the other option is that the GUI doesn't really do a good job of showing what's really happening :)

**Comment by gavinking** [comment]
> the other option is that the GUI doesn't do a good job of showing what's really happening :)

In which case it's still my fault :-(

**Comment by quintesse** [comment]
Well the filtering stuff is Eclipse, isn't it?

**Comment by gavinking** [comment]
Nope.
