### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1622]
I'm seeing this error in the log:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.insert(AbstractStringBuilder.java:1005)
	at java.lang.StringBuilder.insert(StringBuilder.java:291)
	at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.appendJavadoc(DocumentationHover.java:901)
	at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.appendJavadoc(DocumentationHover.java:2174)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.appendJavadoc(EclipseDocGenerator.ceylon:183)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.addDoc$priv$(DocGenerator.ceylon:893)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDeclarationDoc$priv$(DocGenerator.ceylon:411)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentationText(DocGenerator.ceylon:380)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentationText(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentation$canonical$(DocGenerator.ceylon:163)
	at com.redhat.ceylon.ide.common.doc.DocGenerator$impl.getDocumentation(DocGenerator.ceylon:161)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentation$canonical$(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getDocumentation(EclipseDocGenerator.ceylon)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getHoverInfo2(EclipseDocGenerator.ceylon:93)
	at com.redhat.ceylon.eclipse.code.hover.EclipseDocGenerator.getHoverInfo2(EclipseDocGenerator.ceylon:72)
	at com.redhat.ceylon.eclipse.code.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:110)
	at com.redhat.ceylon.eclipse.code.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:86)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)
```

**Comment by gavinking** [comment]
This appears to affect both branches.

**Comment by gavinking** [comment]
I have squashed the index out of bounds, but I don't know what was causing it, so this might not be a complete fix.
