### ISSUE TITLE
NPE when visiting annotations with default arguments

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1627]
This looks like it is a bug in the typechecker, but it only happens in Eclipse, not from the CLI so I think the real problem is in the JDT model.

Steps to reproduce:

* create a new project with a new module like this:
```ceylon
native("jvm")
module mymodule "1.0.0" {
	shared import ceylon.net "1.2.0-2";
}
```
* create a new fancy annotation like this one:
```ceylon
import ceylon.language.meta.declaration {
	ClassDeclaration
}
import ceylon.net.http {
	get,
	AbstractMethod
}

shared annotation RouteAnnotation route(String path, AbstractMethod meth = get)
		=> RouteAnnotation(path, meth);

shared final annotation class RouteAnnotation(String path, {AbstractMethod*} meth)
		satisfies OptionalAnnotation<RouteAnnotation, ClassDeclaration> {}

route("/")
class Foo() {}
```

Note that we can omit the second argument when we call `route()` on class `Foo`, everything works fine.

* create a second project, with its own module that imports the first module, then create a new annotated class:

```
import mymodule {
	route
}

route("/")
class Foo() {}
```

Clean build the project, this will generate an error: 

```
the 'ExpressionVisitor' caused an exception visiting a 'Annotation' node: '"java.lang.NullPointerException"' at 'com.redhat.ceylon.model.loader.AbstractModelLoader.getPackageNameForQualifiedClassName(AbstractModelLoader.java:664)'
```

The full stack trace is here:

```
java.lang.NullPointerException
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getPackageNameForQualifiedClassName(AbstractModelLoader.java:664)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.findModuleForClassMirror(JDTModelLoader.java:1701)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertDeclaredTypeToDeclaration(AbstractModelLoader.java:577)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertNonPrimitiveTypeToDeclaration(AbstractModelLoader.java:542)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getNonPrimitiveType(AbstractModelLoader.java:4910)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:4814)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.readObjectValuesAnnotation(AnnotationLoader.java:350)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.loadLiteralAnnotationTerm(AnnotationLoader.java:251)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.loadAnnotationConstructorDefaultedParameter(AnnotationLoader.java:215)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.loadAnnotationConstructorDefaultedParameters(AnnotationLoader.java:195)
	at com.redhat.ceylon.compiler.java.loader.AnnotationLoader.setAnnotationConstructor(AnnotationLoader.java:78)
	at com.redhat.ceylon.eclipse.core.model.JDTModelLoader.setAnnotationConstructor(JDTModelLoader.java:1787)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:4243)
	at com.redhat.ceylon.model.loader.model.LazyFunction.load(LazyFunction.java:83)
	at com.redhat.ceylon.model.loader.model.LazyFunction.getTypeParameters(LazyFunction.java:118)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.getInvokedProducedReference(ExpressionVisitor.java:2979)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.inferParameterTypesDirectly(ExpressionVisitor.java:2871)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.inferParameterTypes(ExpressionVisitor.java:2784)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:2747)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:300)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Annotation.visit(Tree.java:7752)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAnnotationList(Walker.java:1754)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AnnotationList.visitChildren(Tree.java:7812)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:302)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AnnotationList.visit(Tree.java:7804)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkDeclaration(Walker.java:137)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkTypeDeclaration(Walker.java:147)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassOrInterface(Walker.java:153)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAnyClass(Walker.java:232)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:246)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:2031)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:2043)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ExpressionVisitor.visit(ExpressionVisitor.java:204)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.analyseTypes(PhasedUnit.java:415)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$9$1.call(CeylonBuilder.java:2100)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$9$1.call(CeylonBuilder.java:2013)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:320)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$9.call(CeylonBuilder.java:2013)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$9.call(CeylonBuilder.java:1994)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:269)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.fullTypeCheck(CeylonBuilder.java:1994)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:964)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

I also get backend errors, but I guess they are also due to the fact that something is wrong in the JDT model:

```
compiler bug: null at com.redhat.ceylon.compiler.java.codegen.AnnotationInvocationVisitor.transformConstructor(AnnotationInvocationVisitor.java:231)
```

**Comment by xkr47** [comment]
:+1: fails in eclipse, works when compiled from command line

**Comment by bjansen** [comment]
Investigating further, the following Ceylon code:

```ceylon
shared annotation RouteAnnotation route(String path, AbstractMethod meth = get)
        => RouteAnnotation(path, meth);
```

produces the following Java code:

```java
    @.com.redhat.ceylon.compiler.java.metadata.ObjectValue(.ceylon.net.http.get_.class)
    @.com.redhat.ceylon.compiler.java.metadata.Ignore
    public static final .ceylon.net.http.AbstractMethod route$meth(final .java.lang.String path) {
        return .ceylon.net.http.get_.get_();
    }
```

and when `AnnotationLoader.readObjectValuesAnnotation()` is called on the `ObjectValue` annotation, `.ceylon.net.http.get_.class` is resolved to an `UnresolvedReferenceBinding`, which produces a  `JDTType` with `declaredClass = null`, which is the cause of the NPE.

**Comment by davidfestal** [comment]
could it a problem of visibility in the specific case of your project ?

**Comment by bjansen** [comment]
The annotation is shared, in a shared package. `ceylon.net` is also a shared import, so I think the visibility is correct. Also, the CLI seems to build just fine.

**Comment by bjansen** [comment]
I forgot to mention that if I put a breakpoint in the constructor of `JDTType`, I get two hits for the type `ceylon.net.http.get_` (the default value in my annotation):

* the first time, I get an `UnresolvedReferenceBinding` ("Unresolved type ceylon.net.http.get_")
* the second time, I get a correct `BinaryTypeBinding`

**Comment by davidfestal** [comment]
@bjansen : could share in a Gist the stackTrace of both frames, of both cases (unresolved and resolved) ?

**Comment by davidfestal** [comment]
@bjansen : the NPE occurs after the second hit but visibly uses the JDTType that was created at the first hit. That's why I would like to understand when exactly (stack trace) the 2 hits are created.

**Comment by bjansen** [comment]
https://gist.github.com/bjansen/b2c6b26ef166e58f3eff

I just noticed that I get 3 hits during the initial build (I named them 1, 2, 3 in the gist).

**Comment by davidfestal** [comment]
could you determine which of these JDTType is the JDType that finally has the UnresolvedReferenceBinding ?

**Comment by bjansen** [comment]
[Archive.zip](https://github.com/ceylon/ceylon-ide-eclipse/files/57353/Archive.zip)

Here's a simple project to reproduce the problem.

**Comment by davidfestal** [comment]
Thanks !
