### ISSUE TITLE
"was unexpectedly a member" compiler bug

### ISSUE THREAD

**Issue by ASzc** [ceylon/ceylon-ide-eclipse#1629]
I'm currently working on [ceylon.buffer](https://github.com/ASzc/ceylon-sdk/tree/io-buffer-split/source/ceylon/buffer), and am unable to execute tests because of backend errors in the IDE, maybe related to Java interop.

I've have created an entirely fresh eclipse instance to try and fix this, but the problem persists. How to reproduce:

Compile an IDE update site from `master`, I have these commits in my build environment:
```
de97e0efcf9f1128d7ca7500e0643f31a2306d9d ceylon
135ae3c90fa2271d7c4a272b68faef6489763a13 ceylon.formatter
1de44a24833da5c41c297a7e50da439d61cf43ec ceylon-ide-common
d0a8a591a94780203597a7bf6e66590d85193c92 ceylon-ide-eclipse
7bc42f8caa5060a9c341165f0cadfca2c124a910 ceylon-ide-intellij
33d00f9abd5b26215dee977fe1b7f57cac482be0 ceylon-sdk
d3203449bb0cf1c64584edcf6519c412643a65be ceylon.tool.converter.java2ceylon
```
Create a fresh isolated Eclipse instance (I have Eclipse Mars 4.5.1):
```
eclipse -configuration "$HOME/.eclipse/ceylon-test/config" -data "$HOME/workspace-ceylon-test" -vmargs -XX:MaxPermSize=8192m -Xmx8192m
```
Install `Ceylon IDE` from the local update site and restart. Then clone my SDK branch into the workspace:
```
$ cd ~/workspace-ceylon-test
$ git clone git@github.com:ASzc/ceylon-sdk.git
$ git -C ceylon-sdk checkout io-buffer-split
```
Then `File > Import > Existing Projects Into Workspace`, select the already existing directory in the workspace, hit Finish, and allow the initial compile to complete.

After it is compiled, errors appear for one of the `test.ceylon` modules. These errors appear again in unrelated modules when I delete the module. Here are some sets of errors:

```
Description Resource    Path    Location    Type
compiler bug: ceylon.buffer.codec::ByteToByteCodec.decode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 67 Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 67 Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 67 Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    wholeTests.ceylon   /ceylon-sdk/test-source/test/ceylon/math    line 70 Ceylon Backend Error
Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation.
The detail of missing classes is given in the Information markers.  ceylon-sdk      Unknown Ceylon Backend Error

Description Resource    Path    Location    Type
compiler bug: ceylon.buffer.codec::ByteToByteCodec.decode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 123    Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 119    Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 121    Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 119    Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 121    Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)  streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 123    Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 119    Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 121    Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown    streamTests.ceylon  /ceylon-sdk/test-source/test/ceylon/json/stream line 123    Ceylon Backend Error
Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation.
The detail of missing classes is given in the Information markers.  ceylon-sdk      Unknown Ceylon Backend Error

Description	Resource	Path	Location	Type
compiler bug: ceylon.buffer.codec::ByteToByteCodec.decode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	mutableSet.ceylon	/ceylon-sdk/test-source/test/ceylon/collection	line 65	Ceylon Backend Error
Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation.
The detail of missing classes is given in the Information markers.	ceylon-sdk		Unknown	Ceylon Backend Error
```

Eventually after deleting 2-4 modules they will point at the `ceylon.buffer.ByteBuffer` test:

```
Description	Resource	Path	Location	Type
compiler bug: ceylon.buffer.codec::ByteToByteCodec.decode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
compiler bug: visitor didn't yield any result at unknown	ByteBuffer.ceylon	/ceylon-sdk/test-source/test/ceylon/buffer	line 35	Ceylon Backend Error
Some classes are missing from the generated module archives, probably because of an error in the Java backend compilation.
The detail of missing classes is given in the Information markers.	ceylon-sdk		Unknown	Ceylon Backend Error
```

There are no error markers in the file itself when you open it. Attempting to do anything with the module results in the tests not being found. Executing `test.ceylon.buffer::asd` as a Ceylon Java Application for example:
```
ceylon run: Could not find toplevel function 'test.ceylon.buffer.asd'.
```

**Comment by ASzc** [comment]
Next week I'm going to have a lot of time to work on the SDK. So, if we could get this resolved before then that would be great. Thanks.

**Comment by gavinking** [comment]
@ASzc I just rebuilt and updated the IDE and reinstalled it in Eclipse 4.5.1. I was able to compile the whole SDK and run the test suite. Apart from some failures in the tests for `ceylon.test`, I did not notice any problems.

**Comment by ASzc** [comment]
@gavinking Thanks for checking. I don't know what would be different with my environment then. Does JDK version make a difference? I have OpenJDK 7 and 8 installed, with 7 as the default and only 7 configured in Eclipse.

**Comment by gavinking** [comment]
I was using 8 I believe.

**Comment by ASzc** [comment]
I've tried the following:

- Running Eclipse with JDK 8
  - Same errors as originally described
- Updating, recompiling the IDE with JDK 8, running with JDK 8
  - Old errors are still present, and the transactions module also breaks.
- Recompiling the IDE with JDK 7, running with JDK 8
  - Same errors as originally described, plus the transactions module stayed broken. I'm assuming something in the new commits broke this rather than JDK 8 vs 7.
  - For some reason this time I had to delete these modules to get the original errors to appear:
    - test.ceylon.test
    - test.ceylon.transaction
    - ceylon.transaction

For each of these, I have restarted and run a full workspace clean. These are the new IDE build commit-ids:

```
5072c1db8483b7b2c14d6ff43ed89a68f1649f59 ceylon
f8d1e20c95b4eaf2766ab79c498f14c041ece778 ceylon.formatter
8f0cd582ccdeab8e673a6b602f5b03bc5ad3c256 ceylon-ide-common
0c6e405fa22c5a88194297a8adffa6dd6c86b5e8 ceylon-ide-eclipse
5aa6b03ca197dece63fb4f0cf2d395a564736ba0 ceylon-ide-intellij
5f6cbf26744b1c43bd8ece47320ae78b582674ce ceylon-sdk
8da034a1f925b71e317134a0793856159654550e ceylon.tool.converter.java2ceylon
```

My SDK working commit is the same as before (`io-buffer-split` branch):

```
a6926431b05a9439441d3f5ee3f4ad5aaa150267 ceylon-sdk
```

I also tried to use the CLI to compile, and I actually got the same errors there, so maybe this isn't an IDE bug?

```
[alex@elendil ceylon-sdk] (io-buffer-split +=)$ ceylon-git --version
ceylon version 1.2.1 5072c1d (A Series Of Unlikely Explanations)
[alex@elendil ceylon-sdk] (io-buffer-split +=)$ ceylon-git compile
./source/ceylon/net/http/server/internal/ResponseImpl.ceylon:189: warning: declaration is deprecated: 'responseCode'
    shared actual Integer responseStatus => exchange.responseCode;
                                                     ^
./source/ceylon/net/http/server/internal/ResponseImpl.ceylon:190: warning: declaration is deprecated: 'setResponseCode'
    assign responseStatus => exchange.setResponseCode(responseStatus);
                                      ^
./source/ceylon/net/http/server/internal/DefaultServer.ceylon:93: warning: import is never used: 'ByteBufferPool'
	ByteBufferPool
	^
./source/ceylon/net/http/server/internal/RequestImpl.ceylon:13: warning: import is never used: 'contentTypeFormUrlEncoded'
	contentTypeFormUrlEncoded,
	^
./source/ceylon/net/http/server/internal/RequestImpl.ceylon:14: warning: import is never used: 'contentType'
	contentType,
	^
./source/ceylon/net/http/server/internal/websocket/WebSocketProtocolHandshakeHandler.ceylon:90: warning: declaration is deprecated: 'setResponseCode'
            exchange.setResponseCode(404);
                     ^
./source/ceylon/buffer/charset/utf16.ceylon:3: warning: import is never used: 'CharacterBuffer'
    CharacterBuffer
    ^
./source/ceylon/buffer/charset/utf16.ceylon:29: warning: expression has type 'Nothing'
    shared actual Integer decodeBid({Byte*} sample) => nothing;
                                                       ^
./source/ceylon/buffer/charset/utf16.ceylon:30: warning: expression has type 'Nothing'
    shared actual Integer encodeBid({Character*} sample) => nothing;
                                                            ^
./source/ceylon/buffer/charset/ascii.ceylon:35: warning: expression has type 'Nothing'
    shared actual Integer decodeBid({Byte*} sample) => nothing;
                                                       ^
./source/ceylon/buffer/charset/ascii.ceylon:36: warning: expression has type 'Nothing'
    shared actual Integer encodeBid({Character*} sample) => nothing;
                                                            ^
./source/ceylon/buffer/charset/utf8.ceylon:24: warning: expression has type 'Nothing'
    shared actual Integer decodeBid({Byte*} sample) => nothing;
                                                       ^
./source/ceylon/buffer/charset/utf8.ceylon:25: warning: expression has type 'Nothing'
    shared actual Integer encodeBid({Character*} sample) => nothing;
                                                            ^
./source/ceylon/buffer/charset/iso_8859_1.ceylon:40: warning: expression has type 'Nothing'
    shared actual Integer decodeBid({Byte*} sample) => nothing;
                                                       ^
./source/ceylon/buffer/charset/iso_8859_1.ceylon:41: warning: expression has type 'Nothing'
    shared actual Integer encodeBid({Character*} sample) => nothing;
                                                            ^
./test-source/test/ceylon/json/stream/streamTests.ceylon:4: warning: import is never used: 'ParseException'
    ParseException
    ^
./test-source/test/ceylon/collection/list.ceylon:2: warning: import is never used: 'type'
    type
    ^
./test-source/test/ceylon/collection/list.ceylon:9: warning: import is never used: 'assertTrue'
    assertTrue,
    ^
./test-source/test/ceylon/collection/list.ceylon:10: warning: import is never used: 'assertFalse'
    assertFalse
    ^
./test-source/test/ceylon/collection/mutableSet.ceylon:53: warning: declaration does not exist: 'testCycle'
    "This function is called by [[testCycle]] and [[testRepeat]]."
                                  ^
./test-source/test/ceylon/collection/iterableWithNulls.ceylon:251: warning: declaration is never used: 'nullIndexes'
    List<Integer> nullIndexes({Anything*} iterable) {
                  ^
./test-source/test/ceylon/math/decimalTests.ceylon:126: warning: declaration is never used: 'oneThird'
        Decimal oneThird = decimalNumber(1) / decimalNumber(3);
                ^
./test-source/test/ceylon/math/decimalTests.ceylon:150: warning: declaration is never used: 'd'
        Decimal d = decimalNumber(2)^(-2);
                ^
./test-source/test/ceylon/math/wholeTests.ceylon:81: warning: declaration is never used: 'wn'
        Whole wn = wholeNumber(0) ^ wholeNumber(-1);
              ^
./test-source/test/ceylon/math/wholeTests.ceylon:85: warning: declaration is never used: 'wn'
        Whole wn = wholeNumber(0) ^ wholeNumber(-2);
              ^
./test-source/test/ceylon/math/wholeTests.ceylon:97: warning: declaration is never used: 'wn'
        Whole wn = wholeNumber(-2) ^ wholeNumber(-1);
              ^
./test-source/test/ceylon/math/wholeTests.ceylon:101: warning: declaration is never used: 'wn'
        Whole wn = wholeNumber(-2) ^ wholeNumber(-2);
              ^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:7: warning: import is never used: 'assertNotEquals'
    assertNotEquals,
    ^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at unknown
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at unknown
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: ceylon.buffer.codec::ByteToByteCodec.encode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.transformExpression(ExpressionTransformer.java:340)
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: visitor didn't yield any result at unknown
}
^
./test-source/test/ceylon/buffer/ByteBuffer.ceylon:35: error: compiler bug: ceylon.buffer.codec::ByteToByteCodec.decode was unexpectedly a member at com.redhat.ceylon.compiler.java.codegen.ExpressionTransformer.addThisOrObjectQualifierIfRequired(ExpressionTransformer.java:4975)
}
^
Note: Created module ceylon.buffer/1.2.1
Note: Created module test.ceylon.time/1.2.1
Note: Created module test.ceylon.process/1.2.1
Note: Created module test.ceylon.buffer/1.2.1
Note: Created module test.ceylon.interop.java/1.2.1
Note: Created module ceylon.locale/1.2.1
Note: Created module ceylon.test/1.2.1
Note: Created module test.ceylon.locale/1.2.1
Note: Created module ceylon.time/1.2.1
ceylon compile: There were 9 errors
```

**Comment by gavinking** [comment]
Well the IDE is currently broken and @davidfestal is working on it.

**Comment by ASzc** [comment]
I was hoping giving this a month would make it go away, but unfortunately no.The problem persists, even after cleaning/updating everything. I did however manage to get something more useful out of the CLI, and I will be filing a bug for that.
