### ISSUE TITLE
violated is ZipEntryVirtualFile zipEntry=file

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1646]
```
ceylon.language.AssertionError "Assertion failed
	violated is ZipEntryVirtualFile zipEntry=file"
	at com.redhat.ceylon.ide.common.model.IdeModuleSourceMapper$1anonymous_1_.parseFileInPackage(IdeModuleSourceMapper.ceylon:213)
	at com.redhat.ceylon.ide.common.model.IdeModuleSourceMapper$1anonymous_1_.parseFile(IdeModuleSourceMapper.ceylon:208)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.parseFileOrDirectory(PhasedUnits.java:157)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.processDirectory(PhasedUnits.java:219)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.parseFileOrDirectory(PhasedUnits.java:154)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.processDirectory(PhasedUnits.java:219)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.parseFileOrDirectory(PhasedUnits.java:154)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.parseUnit(PhasedUnits.java:97)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnits.parseUnit(PhasedUnits.java:88)
	at com.redhat.ceylon.ide.common.model.IdeModuleSourceMapper$1anonymous_1_.parseUnit(IdeModuleSourceMapper.ceylon:263)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleSourceMapper.resolveModule(ModuleSourceMapper.java:320)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.resolveModule(LazyModuleSourceMapper.java:121)
	at com.redhat.ceylon.ide.common.model.BaseIdeModuleSourceMapper.resolveModule(IdeModuleSourceMapper.ceylon:136)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:265)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$400(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:112)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:48)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:73)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:96)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.createTypeChecker(CeylonParseController.java:480)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.access$300(CeylonParseController.java:117)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$7.call(CeylonParseController.java:838)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController$7.call(CeylonParseController.java:823)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:325)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.parseAndTypecheck(CeylonParseController.java:823)
	at com.redhat.ceylon.eclipse.code.parse.CeylonParserScheduler.run(CeylonParserScheduler.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
I thought this was already solved in the last couple of days?

**Comment by davidfestal** [comment]
I thought also. I'm looking into it to see if I forgot something
