### ISSUE TITLE
rename refactoring error in 1.2.0 maintenance update

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1650]
No idea if this is a regression, but rename refactoring of a function parameter failed as shown:

<img width="733" alt="screen shot 2015-12-11 at 6 17 15 pm" src="https://cloud.githubusercontent.com/assets/236050/11757997/f4c36c84-a033-11e5-90f9-26a147a2aec5.png">

```
!SUBENTRY 1 org.eclipse.ltk.core.refactoring 4 10001 2015-12-11 18:16:51.848
!MESSAGE End position lies outside document range
!STACK 0
org.eclipse.text.edits.MalformedTreeException: End position lies outside document range
        at org.eclipse.text.edits.TextEditProcessor.checkIntegrityDo(TextEditProcessor.java:178)
        at org.eclipse.text.edits.TextEdit.dispatchCheckIntegrity(TextEdit.java:743)
        at org.eclipse.text.edits.TextEditProcessor.performEdits(TextEditProcessor.java:151)
        at org.eclipse.ltk.core.refactoring.TextChange.performEdits(TextChange.java:277)
        at org.eclipse.ltk.core.refactoring.TextFileChange.access$0(TextFileChange.java:1)
        at org.eclipse.ltk.core.refactoring.TextFileChange$1.run(TextFileChange.java:279)
        at org.eclipse.ui.internal.editors.text.UISynchronizationContext.run(UISynchronizationContext.java:34)
        at org.eclipse.core.internal.filebuffers.TextFileBufferManager.execute(TextFileBufferManager.java:629)
        at org.eclipse.ltk.core.refactoring.TextFileChange.performEdits(TextFileChange.java:291)
        at org.eclipse.ltk.core.refactoring.TextChange.perform(TextChange.java:238)
        at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:278)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:258)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:306)
        at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:223)
        at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:106)
        at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:729)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
        at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5409)
        at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
        at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
        at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2156)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2152)
        at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:191)
        at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:151)
        at com.redhat.ceylon.eclipse.code.refactor.RenameLinkedMode.done(RenameLinkedMode.java:91)
        at com.redhat.ceylon.eclipse.code.refactor.AbstractLinkedMode$2.left(AbstractLinkedMode.java:101)
        at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:341)
        at org.eclipse.jface.text.link.LinkedModeUI$4.run(LinkedModeUI.java:1193)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by davidfestal** [comment]
@jvasileff : I was not able to reproduce this.

**Comment by jvasileff** [comment]
@davidfestal me neither! I'm willing to chalk it up to an exceedingly rare race condition.

**Comment by gavinking** [comment]
I also tried, FTR, couldn't either.

**Comment by davidfestal** [comment]
@jvasileff : can we close this one ?

**Comment by jvasileff** [comment]
Sure, let's close it. It's only happened once.
