### ISSUE TITLE
Import of old language version causes problems in "Ceylon explorer"

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-eclipse#1667]
I have a project lying around where I can't open the source folders anymore. When opening the project I see it has both `source` and `test` Ceylon source folders with the small triangle in front of them to expand them but when I click that both folders show up empty.

The error in the Eclipse log shows the following:

```

!ENTRY com.redhat.ceylon.eclipse.ui 1 0 2016-01-13 18:01:31.307
!MESSAGE [Trying to look up module from ceylon.language.$module_]

!ENTRY com.redhat.ceylon.eclipse.ui 1 0 2016-01-13 18:01:31.332
!MESSAGE [Trying to look up module from ceylon.collection.$module_]

!ENTRY org.eclipse.core.jobs 4 2 2016-01-13 18:01:32.707
!MESSAGE An internal error occurred during: "Initializing dependencies for project ceylon-tako-sdk".
!STACK 0
com.redhat.ceylon.compiler.typechecker.exceptions.LanguageModuleNotFoundException: cannot find module source artifact ceylon.language-null(.car|.jar|.src)
	- dependency tree: org.codejive.ceylon.httpd/1.2.2 -> org.codejive.ceylon.options/1.5.0 -> ceylon.collection/1.1.0 -> ceylon.language/null
	get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleHelper.buildErrorOnMissingArtifact(ModuleHelper.java:50)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:240)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:271)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:271)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$400(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:112)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:48)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:73)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:96)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2328)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2148)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:274)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2148)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2145)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:321)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2145)
	at com.redhat.ceylon.eclipse.core.classpath.CeylonProjectModulesContainer.resolveClasspath(CeylonProjectModulesContainer.java:312)
	at com.redhat.ceylon.eclipse.core.classpath.InitDependenciesJob.run(InitDependenciesJob.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.redhat.ceylon.eclipse.ui 1 0 2016-01-13 18:01:32.817
!MESSAGE [Trying to look up module from ceylon.language.$module_]

!ENTRY com.redhat.ceylon.eclipse.ui 1 0 2016-01-13 18:01:32.837
!MESSAGE [Trying to look up module from ceylon.collection.$module_]

!ENTRY org.eclipse.core.resources 4 2 2016-01-13 18:01:33.819
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
com.redhat.ceylon.compiler.typechecker.exceptions.LanguageModuleNotFoundException: cannot find module source artifact ceylon.language-null(.car|.jar|.src)
	- dependency tree: org.codejive.ceylon.httpd/1.2.2 -> org.codejive.ceylon.options/1.5.0 -> ceylon.collection/1.1.0 -> ceylon.language/null
	get ceylon.language and run 'ant publish' (more information at http://ceylon-lang.org/code/source/#ceylonlanguage_module)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleHelper.buildErrorOnMissingArtifact(ModuleHelper.java:50)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:240)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:271)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:271)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.access$400(ModuleValidator.java:39)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:112)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:48)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:73)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:96)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2328)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10$1.call(CeylonBuilder.java:2148)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:274)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2148)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$10.call(CeylonBuilder.java:2145)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:321)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.parseCeylonModel(CeylonBuilder.java:2145)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:952)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by quintesse** [comment]
The errors are most likely due to old code still referencing old language module versions, but that shouldn't cause problems in the IDE of course.

**Comment by davidfestal** [comment]
Now the error is added in the Problems view. Closing

**Comment by quintesse** [comment]
Cool! I'll test in a moment!

**Comment by quintesse** [comment]
Ok, the real problem has disappered! Great!

I *do* still have a pop-up error from the IDE each time I open one of my projects:

```

!ENTRY com.redhat.ceylon.eclipse.ui 4 0 2016-01-15 17:56:26.274
!MESSAGE Ceylon class ceylon.interop.java.javaString_ was compiled by an incompatible version of the Ceylon compiler
The class was compiled using 7.0.
This compiler supports 8.0.
Please try to recompile your module using a compatible compiler.
Binary compatibility will only be supported after Ceylon 1.2.

!ENTRY org.eclipse.core.jobs 4 2 2016-01-15 17:56:26.304
!MESSAGE An internal error occurred during: "Initial build of project ceylon-tako-sdk".
!STACK 0
ceylon.language.AssertionError "Assertion failed
	violated is BaseIdeModule mod"
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:745)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:744)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.loadPackage(IdeModelLoader.ceylon:801)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.findExistingPackage(AbstractModelLoader.java:1734)
	at com.redhat.ceylon.model.loader.model.LazyModule.findPackageInModule(LazyModule.java:122)
	at com.redhat.ceylon.model.loader.model.LazyModule.findPackageInImport(LazyModule.java:94)
	at com.redhat.ceylon.model.loader.model.LazyModule.getPackage(LazyModule.java:62)
	at com.redhat.ceylon.model.loader.TypeParser.loadType(TypeParser.java:675)
	at com.redhat.ceylon.model.loader.TypeParser.parseBaseType(TypeParser.java:651)
	at com.redhat.ceylon.model.loader.TypeParser.parseQualifiedType(TypeParser.java:578)
	at com.redhat.ceylon.model.loader.TypeParser.parseAtomicType(TypeParser.java:243)
	at com.redhat.ceylon.model.loader.TypeParser.parsePrimaryType(TypeParser.java:222)
	at com.redhat.ceylon.model.loader.TypeParser.parseIntersectionType(TypeParser.java:195)
	at com.redhat.ceylon.model.loader.TypeParser.parseUnionType(TypeParser.java:172)
	at com.redhat.ceylon.model.loader.TypeParser.parseType(TypeParser.java:155)
	at com.redhat.ceylon.model.loader.TypeParser.decodeType(TypeParser.java:129)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.decodeType(AbstractModelLoader.java:4723)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.decodeType(AbstractModelLoader.java:4718)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setListOfTypes(AbstractModelLoader.java:4631)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setTypeParametersFromAnnotations(AbstractModelLoader.java:4599)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.setTypeParameters(AbstractModelLoader.java:4704)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.completeTypeParameters(AbstractModelLoader.java:2234)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.completeTypeParameters(AbstractModelLoader.java:2132)
	at com.redhat.ceylon.model.loader.model.LazyClass.loadTypeParams(LazyClass.java:109)
	at com.redhat.ceylon.model.loader.model.LazyClass.getTypeParameters(LazyClass.java:166)
	at com.redhat.ceylon.compiler.typechecker.analyzer.AnalyzerUtil.isGeneric(AnalyzerUtil.java:1079)
	at com.redhat.ceylon.compiler.typechecker.analyzer.AnalyzerUtil.unwrapAliasedTypeConstructor(AnalyzerUtil.java:1163)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visitSimpleType(TypeVisitor.java:541)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:407)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$BaseType.visit(Tree.java:2001)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkTypedDeclaration(Walker.java:307)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAnyAttribute(Walker.java:311)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkAttributeDeclaration(Walker.java:315)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visitChildren(Tree.java:1272)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:93)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:49)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:661)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:50)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:1512)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:51)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:1078)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$AttributeDeclaration.visit(Tree.java:1264)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:429)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:438)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1845)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:70)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1837)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:93)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:744)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkBody(Walker.java:429)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassBody(Walker.java:438)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visitChildren(Tree.java:1845)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:68)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:70)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassBody.visit(Tree.java:1837)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkClassDefinition(Walker.java:248)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visitChildren(Tree.java:949)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:93)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:40)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:41)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:744)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$ClassDefinition.visit(Tree.java:941)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.analyzer.TypeVisitor.visit(TypeVisitor.java:89)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.compiler.typechecker.context.PhasedUnit.scanTypeDeclarations(PhasedUnit.java:383)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$8$1.call(CeylonBuilder.java:2069)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$8$1.call(CeylonBuilder.java:2002)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:318)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$8.call(CeylonBuilder.java:2002)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$8.call(CeylonBuilder.java:1983)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:271)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.fullTypeCheck(CeylonBuilder.java:1983)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:1006)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:486)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:405)
	at com.redhat.ceylon.eclipse.core.classpath.BuildProjectAfterClasspathChangeJob.run(BuildProjectAfterClasspathChangeJob.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
Oh, OK, unexpected. I fixed it in the distribution code, and tested it in the upcoming 1.2.1 IDE, but not on IDE master. it seems there is a case I had not expected on master

**Comment by davidfestal** [comment]
@quintesse : I've not been able to reproduce your last error, even on master. Do you have a systematic way to reproduce it ? Normally, there should never be only `BaseIdeModule` instances inside the IDE.

**Comment by quintesse** [comment]
Right now I can't reproduce it anymore so let's close this for now.
