### ISSUE TITLE
NPE from Open dialog

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1672]
I just got:

```
!ENTRY org.eclipse.core.jobs 4 2 2016-01-19 13:22:22.156
!MESSAGE An internal error occurred during: "Items filtering".
!STACK 0
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.convertToDeclaration(IdeModelLoader.ceylon:506)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3$1.$call$(IdeModelLoader.ceylon:788)
	at ceylon.language.Iterable$impl.each(Iterable.ceylon:323)
	at ceylon.language.impl.BaseIterable.each(bases.ceylon)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:782)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader$3.$call$(IdeModelLoader.ceylon:744)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.IdeModelLoader.loadPackage(IdeModelLoader.ceylon:801)
	at com.redhat.ceylon.model.loader.model.LazyPackage.getMembers(LazyPackage.java:177)
	at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.fill(OpenDeclarationDialog.java:953)
	at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.fillContentProvider(OpenDeclarationDialog.java:935)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2235)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2186)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2158)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2145)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

@davidfestal would you take a look please?

**Comment by davidfestal** [comment]
I've fixed the obvious root cause of such an error at this line. @gavinking : Do you confirm that this also fixes the problem you had encountered ?
