### ISSUE TITLE
exception using "Find References"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1673]
Right clicking on `CeylonIterable` and choosing "Find References" caused this exception:

```
!ENTRY org.eclipse.ui 4 4 2016-01-20 19:32:00.448
!MESSAGE An internal error has occurred.
!STACK 0
com.redhat.ceylon.compiler.java.language.EnumeratedTypeError: Supposedly exhaustive switch was not exhaustive
        at com.redhat.ceylon.ide.common.model.BaseIdeModuleManager.getArchiveModuleFromSourcePath(IdeModuleManager.ceylon:182)
        at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.getUnit(CeylonBuilder.java:3995)
        at com.redhat.ceylon.eclipse.code.search.CeylonSearchResultTreeContentProvider.getParent(CeylonSearchResultTreeContentProvider.java:407)
        at com.redhat.ceylon.eclipse.code.search.CeylonSearchResultTreeContentProvider.insert(CeylonSearchResultTreeContentProvider.java:155)
        at com.redhat.ceylon.eclipse.code.search.CeylonSearchResultTreeContentProvider.elementsChanged(CeylonSearchResultTreeContentProvider.java:129)
        at com.redhat.ceylon.eclipse.code.search.CeylonSearchResultPage.elementsChanged(CeylonSearchResultPage.java:163)
        at org.eclipse.search.ui.text.AbstractTextSearchViewPage.runBatchedUpdates(AbstractTextSearchViewPage.java:1253)
        at org.eclipse.search.ui.text.AbstractTextSearchViewPage.access$1(AbstractTextSearchViewPage.java:1252)
        at org.eclipse.search.ui.text.AbstractTextSearchViewPage$UpdateUIJob.runInUIThread(AbstractTextSearchViewPage.java:146)
        at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by gavinking** [comment]
Any idea @bjansen @davidfestal ?
