### ISSUE TITLE
error editing '.ceylon' file in non-Ceylon project

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1675]
Opening and saving `x.ceylon` files in a non-Ceylon project results in an error dialog with:

```
An internal error occurred during: "Parsing and typechecking dartExtras.ceylon".
Assertion failed
	violated exists existingCeylonProject = ceylonModel.getProject(nativeResource.project)
```

This project very similar to the `ceylon/language`, with an identical `.project` config, but for some reason I'm only seeing this error in my project. Perhaps the difference is that in the project with errors, the Ceylon source files are in a `source` directory, as opposed to `src` for the `ceylon.language` project.

My project's config is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
        <name>ceylon-dart-language</name>
        <comment></comment>
        <projects>
        </projects>
        <buildSpec>
                <buildCommand>
                        <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
        </buildSpec>
        <natures>
                <nature>org.eclipse.jdt.core.javanature</nature>
        </natures>
</projectDescription>
```

*Edit* corrected: I'm *only* seeing this error in my project, not the dist one.

**Comment by jvasileff** [comment]
Oh, I see, the difference is that in the project with errors, the `source` directory is listed in `.classpath`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
        <classpathentry kind="src" path="source"/>
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
        <classpathentry kind="output" path="classes"/>
</classpath>
```

Changing to `path="DISABLED"` silences the errors.

**Comment by davidfestal** [comment]
OK, right. it's related to a recent change. I'll fix that asap.

**Comment by davidfestal** [comment]
@jvasileff : would you have a stacktrace ?

**Comment by jvasileff** [comment]
Here you go:
```
!ENTRY org.eclipse.core.jobs 4 2 2016-01-25 13:43:43.156
!MESSAGE An internal error occurred during: "Parsing and typechecking run.ceylon".
!STACK 0
ceylon.language.AssertionError "Assertion failed
        violated exists existingCeylonProject = ceylonModel.getProject(nativeResource.project)"
        at com.redhat.ceylon.eclipse.core.vfs.IFolderVirtualFile.<init>(eclipseVFS.ceylon:56)
        at com.redhat.ceylon.eclipse.core.model.ceylonModel_$VirtualFileSystem.createVirtualFolderFromProject(EclipseCeylonProjects.ceylon:46)
        at com.redhat.ceylon.eclipse.core.model.ceylonModel_$VirtualFileSystem.createVirtualFolderFromProject(EclipseCeylonProjects.ceylon:32)
        at com.redhat.ceylon.eclipse.core.vfs.vfsJ2C.createVirtualFolder(vfsJ2C.java:48)
        at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.getSourceFolder(CeylonParseController.java:610)
        at com.redhat.ceylon.eclipse.code.parse.CeylonParseController.parseAndTypecheck(CeylonParseController.java:793)
        at com.redhat.ceylon.eclipse.code.parse.CeylonParserScheduler.run(CeylonParserScheduler.java:118)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
@jvasileff : Do you confirm this works on your side after the fix?

**Comment by jvasileff** [comment]
@davidfestal works great, thanks!
