### ISSUE TITLE
NPE using stale "Ceylon Type Hierarchy"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1676]
I've repeated this process twice:

1) Use F4 to populate the Ceylon Type Hierarchy
2) Edit one of the classes
3) Save
4) Click on another class in the hierarchy. An error dialog appears reporting a NPE.

At this point, NPEs happen when clicking on *most* of the nodes (clicking on Anything, Object, and Basic do not result in exceptions.)

Actually, make that three times. The last repro involved only whitespace changes.

````
!ENTRY org.eclipse.jface 4 2 2016-01-21 20:48:01.468
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
        at com.redhat.ceylon.ide.common.model.ProjectSourceFile.getResourceProject(ProjectSourceFile.ceylon:66)
        at com.redhat.ceylon.eclipse.util.ModelProxy.<init>(ModelProxy.java:72)
        at com.redhat.ceylon.eclipse.code.outline.HierarchyView$11.selectionChanged(HierarchyView.java:710)
        at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
        at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
        at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:160)
        at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2197)
        at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1228)
        at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1257)
        at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
        at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:236)
        at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:408)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by davidfestal** [comment]
This was visibly fixed by commit ceylon-ide-common@519dcd341e8c3261f238c21f983b431f4a9acbee
