### ISSUE TITLE
Assertion failed on import proposals during "Retrieving fixes"

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1688]
```
ceylon.language.AssertionError "Assertion failed
	violated exists endIndex=imts.get(imts.size() - 1).endIndex"
	at com.redhat.ceylon.ide.common.correct.ImportProposals$impl.getBestImportMemberInsertPosition(ImportProposals.ceylon:334)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.getBestImportMemberInsertPosition(ImportProposals.ceylon)
	at com.redhat.ceylon.ide.common.correct.ImportProposals$impl.importEdits(ImportProposals.ceylon:176)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.importEdits(ImportProposals.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.importEdits(ImportProposals.ceylon:37)
	at com.redhat.ceylon.ide.common.correct.ImportProposals$impl.createImportProposal(ImportProposals.ceylon:109)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.createImportProposal(ImportProposals.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.createImportProposal(ImportProposals.ceylon:37)
	at com.redhat.ceylon.ide.common.correct.ImportProposals$impl.addImportProposals(ImportProposals.ceylon:65)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.addImportProposals(ImportProposals.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseImportProposals_.addImportProposals(ImportProposals.ceylon:37)
	at com.redhat.ceylon.ide.common.correct.IdeQuickFixManager.addQuickFixes(IdeQuickFixManager.ceylon:57)
	at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:46)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:620)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:502)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
@bjansen : do you think you would have the time to have a look at this one ? Thanks !

**Comment by bjansen** [comment]
How can I reproduce this? It looks like an import statement needs to contain a parsing error to force `endIndex` to be `null`, but I couldn't trigger that.

**Comment by davidfestal** [comment]
Don't know exactly how it happened.Maybe during a parsing or typechecking.

**Comment by bjansen** [comment]
I was able to reproduce it with an unclosed import statement: 

```ceylon
import ceylon.net.http {
	

void run() {
	allow
}
```
