### ISSUE TITLE
`StringIndexOutOfBoundsException` in doc hover when navigating to a module link

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1689]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -21
	at java.lang.String.substring(String.java:1954)
	at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.getLinkedModel(DocumentationHover.java:268)
	at com.redhat.ceylon.eclipse.code.hover.DocumentationHover.getLinkedModel(DocumentationHover.java:245)
	at com.redhat.ceylon.eclipse.code.hover.CeylonLocationListener.handleLink(CeylonLocationListener.java:89)
	at com.redhat.ceylon.eclipse.code.hover.CeylonLocationListener.changing(CeylonLocationListener.java:41)
	at org.eclipse.swt.browser.WebKit.webkit_navigation_policy_decision_requested(WebKit.java:1956)
	at org.eclipse.swt.browser.WebKit.webViewProc(WebKit.java:571)
	at org.eclipse.swt.browser.WebKit.Proc(WebKit.java:450)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9279)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1225)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2425)
```

**Comment by davidfestal** [comment]
Fixed by 67abb05ab5c93df899a012cea615adc3d3e444e2
