### ISSUE TITLE
Ceylon plugin doesn't seem to be available from the update site

### ISSUE THREAD

**Issue by ttobin62** [ceylon/ceylon-ide-eclipse#1697]
When I try to install the plugin using eclipse all I see are the GEF components:

![ceylon-plugin-updatesite](https://cloud.githubusercontent.com/assets/17276180/13213490/3bf585c4-d941-11e5-9b50-1229bcec7308.png)

**Comment by davidfestal** [comment]
@ttobin62 : what happens if you uncheck "Hide items that are already installed" ?

**Comment by ttobin62** [comment]
2 more GEF items appear. No Ceylon items.

Tim

**Comment by davidfestal** [comment]
@ttobin62 : Could you go into the "Available Software Sites" dialog, and reload the Eclipse update site ? You might have some wrong cached information about this update site. And retry then. I've just tried on a fresh Mars installation, and it works well.
Could you also give more information about your configuration, OS, proxy, etc ... And look in you have some errors reported in the Eclipse log ?

**Comment by ttobin62** [comment]
I have the following from the eclipse log:

!ENTRY org.eclipse.equinox.p2.core 4 0 2016-02-22 10:15:08.882
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: HTTP Server Unknown HTTP Response Code (301):http://downloads.ceylon-lang.org/ide/eclipse/prod/content.xml
                at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:243)
                at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
                at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
                at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:337)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:144)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:387)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
                at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.addChild(CompositeMetadataRepository.java:166)
                at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository.<init>(CompositeMetadataRepository.java:106)
                at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:122)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
                at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:116)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:337)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:144)
                at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:387)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
                at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:92)
                at org.eclipse.equinox.p2.ui.ProvisioningUI.loadMetadataRepository(ProvisioningUI.java:440)
                at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.getMetadataRepository(MetadataRepositoryElement.java:126)
                at org.eclipse.equinox.internal.p2.ui.model.MetadataRepositoryElement.fetchChildren(MetadataRepositoryElement.java:75)
                at org.eclipse.equinox.internal.p2.ui.model.RemoteQueriedElement.fetchDeferredChildren(RemoteQueriedElement.java:34)
                at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:232)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.ecf.filetransfer.BrowseFileTransferException: General connection error with response code=301
                at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:131)
                at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
                ... 1 more
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2016-02-22 10:15:08.884
!MESSAGE HTTP Server Unknown HTTP Response Code (301):http://downloads.ceylon-lang.org/ide/eclipse/prod/content.xml
!STACK 1
org.eclipse.ecf.filetransfer.BrowseFileTransferException: General connection error with response code=301
                at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:131)
                at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 2 org.eclipse.ecf.identity 4 0 2016-02-22 10:15:08.885
!MESSAGE General connection error with response code=301

It might be to do with this setting:

-Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclient4

Eclipse is unable to deal with the proxy server without this setting.

**Comment by davidfestal** [comment]
what if you add the following update site URL: https://downloads.ceylon-lang.org/ide/eclipse/prod/  ?

**Comment by ttobin62** [comment]
That seems to work.

Thanks David.

Tim

**Comment by davidfestal** [comment]
Do you think you could uninstall the plugin, and retry with the official update site ? I've just made a small change that avoids an automatic http-to-https redirection. This might have been to reason of your problem.

**Comment by ttobin62** [comment]
That works now. The only difference is that the update site provides GEF components whilst the prod site does not.

**Comment by davidfestal** [comment]
Thanks @ttobin62 for your confirmation !
