### ISSUE TITLE
add module import quick fix is broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1704]
The "add module import" quick fix is completely broken, it seems.

**Comment by gavinking** [comment]
@davidfestal @bjansen would you guys take a look, please?

**Comment by bjansen** [comment]
Looks like the same kind of problems as https://github.com/ceylon/ceylon-ide-common/issues/25:

```
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:382)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toProducedType(TypeDescriptor.java:312)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.toType(TypeDescriptor.java:301)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:382)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor.is(TypeDescriptor.java:1366)
	at com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor$Class.is(TypeDescriptor.java:263)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isReified(Metamodel.java:348)
	at com.redhat.ceylon.compiler.java.Util.isReified(Util.java:63)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getDescriptorPhasedUnit$priv$(eclipseModuleImportUtils.ceylon:84)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getUnit(eclipseModuleImportUtils.ceylon:65)
	at com.redhat.ceylon.eclipse.code.imports.eclipseModuleImportUtils_.getUnit(eclipseModuleImportUtils.ceylon:51)
	at com.redhat.ceylon.ide.common.imports.AbstractModuleImportUtil.addModuleImports2(AbstractModuleImportUtil.ceylon:169)
	at com.redhat.ceylon.ide.common.imports.AbstractModuleImportUtil.addModuleImport(AbstractModuleImportUtil.ceylon:104)
	at com.redhat.ceylon.ide.common.correct.AddModuleImportQuickFix$impl.applyChanges(AddModuleImportQuickFix.ceylon:46)
	at com.redhat.ceylon.eclipse.code.correct.eclipseAddModuleImportQuickFix_.applyChanges(addModuleImportQuickFix.ceylon)
```

**Comment by gavinking** [comment]
Thanks!
