### ISSUE TITLE
NPE in correction proposals

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1711]
Not quite #1708 

````
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.code.correct.ChangeDeclarationProposal.addChangeDeclarationProposal(ChangeDeclarationProposal.java:32)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:738)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:517)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by davidfestal** [comment]
@simonthum : does it occur on the release 1.2.1 plugin, or in the master-based just-built plugin ?

**Comment by simonthum** [comment]
1.2.1 release.

**Comment by bjansen** [comment]
@davidfestal make sure you also fix ChangeDeclarationQuickFix on master ;)

**Comment by davidfestal** [comment]
please add a link to the `ceylon-ide-common` file here :-)

**Comment by bjansen** [comment]
https://github.com/ceylon/ceylon-ide-common/blob/master/source/com/redhat/ceylon/ide/common/correct/ChangeDeclarationQuickFix.ceylon

**Comment by davidfestal** [comment]
Thanks !

**Comment by gavinking** [comment]
Probably fixed now.
