### ISSUE TITLE
lots of assertion failures

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1723]
Here's three different bugs I ran into:

- 1

```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.eclipse.code.complete.EclipseInvocationCompletionProposal.getImage(EclipseInvocationCompletionProposal.ceylon:108)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.handleSetData(CompletionProposalPopup.java:865)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$24(CompletionProposalPopup.java:838)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$3.handleEvent(CompletionProposalPopup.java:600)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Table.checkData(Table.java:274)
	at org.eclipse.swt.widgets.Table.tableView_objectValueForTableColumn_row(Table.java:3235)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6000)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:758)
	at org.eclipse.swt.widgets.Table.drawRect(Table.java:1172)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5670)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5051)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5432)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:94)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3692)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

- 2

```
ceylon.language.AssertionError "Assertion failed
	violated is Declaration container = dec.container"
	at com.redhat.ceylon.ide.common.correct.ChangeTypeQuickFix$impl.addChangeTypeProposal$priv$(ChangeTypeQuickFix.ceylon:223)
	at com.redhat.ceylon.ide.common.correct.ChangeTypeQuickFix$impl.addChangeTypeProposalsInternal$priv$(ChangeTypeQuickFix.ceylon:177)
	at com.redhat.ceylon.ide.common.correct.ChangeTypeQuickFix$impl.addChangeTypeProposals(ChangeTypeQuickFix.ceylon:124)
	at com.redhat.ceylon.eclipse.code.correct.eclipseChangeTypeQuickFix_.addChangeTypeProposals(changeTypeQuickFix.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseChangeTypeQuickFix_.addChangeTypeProposals(changeTypeQuickFix.ceylon)
	at com.redhat.ceylon.ide.common.correct.IdeQuickFixManager.addQuickFixes(IdeQuickFixManager.ceylon:245)
	at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:61)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:526)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:407)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

- 3

```
ENTRY org.eclipse.core.jobs 4 2 2016-03-10 11:48:19.132
!MESSAGE An internal error occurred during: "Retrieving Fixes".
!STACK 0
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.correct.ChangeTypeQuickFix$impl.addChangeTypeProposals(ChangeTypeQuickFix.ceylon:128)
	at com.redhat.ceylon.eclipse.code.correct.eclipseChangeTypeQuickFix_.addChangeTypeProposals(changeTypeQuickFix.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseChangeTypeQuickFix_.addChangeTypeProposals(changeTypeQuickFix.ceylon)
	at com.redhat.ceylon.ide.common.correct.IdeQuickFixManager.addQuickFixes(IdeQuickFixManager.ceylon:245)
	at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:61)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:526)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:407)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by bjansen** [comment]
Number 1 was the root cause of #1722.

I can't reproduce the other two, it looks like your model wasn't fully initialized or something like that. Do you have a specific example that fails?

I tested them on this sample:

```ceylon
Integer run(String a = 1) {
	return 1.string;
}
```

The proposals showed up as expected, I didn't have assertion errors.

**Comment by gavinking** [comment]
I have fixed number 2. Eyeballing the code I can't see how 3 could ever reasonably occur.

Closing.
