### ISSUE TITLE
problem with quick fix in unsaved editor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1728]
If I have this code in an _unsaved_ editor:

```ceylon

class Foo(String text) {
    if (1==1) {
        void print() => print(text);
    }
}
```

Then I get this error:

```
ceylon.language.AssertionError "Assertion failed
	violated is Tree.Declaration decNode = fdv.declarationNode"
	at com.redhat.ceylon.ide.common.correct.CreateParameterQuickFix$impl.addCreateParameterProposalsInternal$priv$(CreateParameterQuickFix.ceylon:197)
	at com.redhat.ceylon.ide.common.correct.CreateParameterQuickFix$impl.addCreateParameterProposals(CreateParameterQuickFix.ceylon:166)
	at com.redhat.ceylon.eclipse.code.correct.eclipseCreateParameterQuickFix_.addCreateParameterProposals(createParameterQuickFix.ceylon)
	at com.redhat.ceylon.eclipse.code.correct.eclipseCreateParameterQuickFix_.addCreateParameterProposals(createParameterQuickFix.ceylon)
	at com.redhat.ceylon.ide.common.correct.IdeQuickFixManager.addQuickFixes(IdeQuickFixManager.ceylon:241)
	at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:61)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:526)
	at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:407)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
	at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

The error goes away if I save the editor.

**Comment by gavinking** [comment]
Fixed now, probably.
