### ISSUE TITLE
ceylon.test: StringIndexOutOfBoundsException clicking on JavaScript failure trace

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1745]
For a JavaScript test like:

```ceylon
shared test void someTest() {
    assert(false);
}
```

clicking on the first line in the "Failure Trace" results in the exception below.

Since JavaScript stack traces don't provide ceylon file and line number info, perhaps clicking in this area for JavaScript stack traces should be a no-op.

```
!ENTRY org.eclipse.jface 4 2 2016-03-21 09:29:25.864
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: -61
        at java.lang.String.substring(String.java:1954)
        at com.redhat.ceylon.test.eclipse.plugin.ui.StackTracePanel.gotoStackTraceLine(StackTracePanel.java:152)
        at com.redhat.ceylon.test.eclipse.plugin.ui.StackTracePanel.handleDoubleClick(StackTracePanel.java:138)
        at com.redhat.ceylon.test.eclipse.plugin.ui.StackTracePanel.access$3(StackTracePanel.java:127)
        at com.redhat.ceylon.test.eclipse.plugin.ui.StackTracePanel$1.doubleClick(StackTracePanel.java:122)
        at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:832)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
...
```

**Comment by thradec** [comment]
Fixed, thanks.
