### ISSUE TITLE
Error every time I save a file

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1748]
I'm suddenly getting this error every time I save a file:

```
!MESSAGE An internal error occurred during: "Building workspace".
!STACK 0
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.model.IdeModule$23.$call$(IdeModule.ceylon:962)
	at com.redhat.ceylon.ide.common.model.IdeModule$10.$call$(IdeModule.ceylon:564)
	at com.redhat.ceylon.ide.common.util.synchronize_.synchronize(synchronize_.java:33)
	at com.redhat.ceylon.ide.common.model.IdeModule.doWithPhasedUnitsObject$priv$(IdeModule.ceylon:562)
	at com.redhat.ceylon.ide.common.model.IdeModule.refresh(IdeModule.ceylon:946)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$7.call(CeylonBuilder.java:1719)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$7.call(CeylonBuilder.java:1687)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithSourceModel(CeylonBuilder.java:311)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.incrementalBuild(CeylonBuilder.java:1687)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.access$100(CeylonBuilder.java:211)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$3.call(CeylonBuilder.java:1025)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$3.call(CeylonBuilder.java:1022)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:261)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:1022)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

I can't really tell what actions I did to cause this :/

**Comment by davidfestal** [comment]
@bjansen : do you still have these errors ? The error line doesn't match the current code, soI cannot understand what's going on without reproducing it...

**Comment by bjansen** [comment]
I don't really use Eclipse anymore, so we can probably close this one too.
