### ISSUE TITLE
two new errors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1751]
Found these in the log:

```
ava.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lorg.eclipse.jface.text.contentassist.IContextInformation;
	at com.redhat.ceylon.eclipse.code.complete.EclipseCompletionManager.computeContextInformation(eclipseCompletionManager.ceylon:166)
	at org.eclipse.jface.text.contentassist.ContentAssistant$6.run(ContentAssistant.java:1933)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeContextInformation(ContentAssistant.java:1931)
	at org.eclipse.jface.text.contentassist.ContentAssistSubjectControlAdapter.computeContextInformation(ContentAssistSubjectControlAdapter.java:390)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.computeContextInformation(ContextInformationPopup.java:397)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.access$1(ContextInformationPopup.java:396)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup$1.run(ContextInformationPopup.java:194)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.ContextInformationPopup.showContextProposals(ContextInformationPopup.java:189)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:388)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

And:

```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:985)
	at com.redhat.ceylon.ide.common.util.FindReferencesVisitor.visit(FindReferencesVisitor.ceylon:171)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfClause.visit(Tree.java:3537)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkIfStatement(Walker.java:816)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visitChildren(Tree.java:3516)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:119)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:128)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:134)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$IfStatement.visit(Tree.java:3508)
	at com.redhat.ceylon.ide.common.util.FindReferencesVisitor.visit(FindReferencesVisitor.ceylon:277)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:69)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$Block.visit(Tree.java:1809)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkMethodDefinition(Walker.java:350)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visitChildren(Tree.java:1412)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:49)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:54)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:55)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$MethodDefinition.visit(Tree.java:1404)
	at com.redhat.ceylon.ide.common.util.FindReferencesVisitor.visit(FindReferencesVisitor.ceylon:277)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:71)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$InterfaceBody.visit(Tree.java:1861)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkInterfaceDefinition(Walker.java:295)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$InterfaceDefinition.visitChildren(Tree.java:1158)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:116)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:117)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:26)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:28)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:29)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:46)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:47)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$InterfaceDefinition.visit(Tree.java:1150)
	at com.redhat.ceylon.compiler.typechecker.tree.Walker.walkCompilationUnit(Walker.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visitChildren(Tree.java:30)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visitAny(Visitor.java:10)
	at com.redhat.ceylon.compiler.typechecker.tree.Visitor.visit(Visitor.java:12)
	at com.redhat.ceylon.compiler.typechecker.tree.Tree$CompilationUnit.visit(Tree.java:22)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.getOccurrencesOf(MarkOccurrencesAction.java:641)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.recomputeAnnotationsForSelection(MarkOccurrencesAction.java:262)
	at com.redhat.ceylon.eclipse.code.editor.MarkOccurrencesAction.caretMoved(MarkOccurrencesAction.java:153)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:97)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.custom.StyledText.setCaretOffset(StyledText.java:8644)
	at org.eclipse.swt.custom.StyledText.setSelection(StyledText.java:9684)
	at org.eclipse.swt.custom.StyledText.setSelectionRange(StyledText.java:9733)
	at org.eclipse.jface.text.TextViewer.setSelectedRange(TextViewer.java:2397)
	at org.eclipse.ui.texteditor.AbstractTextEditor.selectAndReveal(AbstractTextEditor.java:6335)
	at org.eclipse.ui.texteditor.AbstractTextEditor.selectAndReveal(AbstractTextEditor.java:6306)
	at com.redhat.ceylon.eclipse.code.editor.Navigation.gotoNode(Navigation.java:145)
	at com.redhat.ceylon.eclipse.code.resolve.CeylonHyperlinkDetector$CeylonNodeLink.open(CeylonHyperlinkDetector.java:53)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseUp(HyperlinkManager.java:436)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:220)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

@bjansen would you take a look at them, please?

**Comment by gavinking** [comment]
Thanks man.
