### ISSUE TITLE
Neon compatibility

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon-ide-eclipse#1766]
I just tested ceylon against Neon M7. Besides an API change already reported, there was this interesting error:

```
org.eclipse.core.internal.resources.ResourceException: Errors occurred during the build.
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:499)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
        at com.redhat.ceylon.eclipse.core.classpath.BuildProjectAfterClasspathChangeJob.run(BuildProjectAfterClasspathChangeJob.java:59)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Contains: Errors running builder 'Integrated External Tool Builder' on project 'com.redhat.ceylon.eclipse.ui'.
org.eclipse.debug.core.DebugException: Launch configuration type id "org.eclipse.ant.AntBuilderLaunchConfigurationType" does not exist.
Possible causes:
        Missing specification of a launch type (missing plug-in)
        Incorrect launch configuration XML
        at org.eclipse.debug.internal.core.LaunchConfigurationInfo.initializeFromXML(LaunchConfigurationInfo.java:525)
        at org.eclipse.debug.internal.core.LaunchManager.createInfoFromXML(LaunchManager.java:955)
```

Perhaps ant has moved or became optional? But maybe only launch configs in the IDE need fixing (I had ceylon IDE projects open).

**Comment by bjansen** [comment]
I believe this issue is now obsolete, I've been using the plugin in Neon.1 for quite a while now, and didn't notice that problem.
