### ISSUE TITLE
NPE if a non-empty resource folder name is a java keyword

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#1773]
For example, if I create a `resource/static/file.html` file, I get:

``
The Ceylon Java backend compilation failed
  with a throwable : java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.tools.JarOutputRepositoryManager$ProgressiveJar.getJavaFileObject(JarOutputRepositoryManager.java:435)
	at com.redhat.ceylon.compiler.java.tools.JarOutputRepositoryManager.getFileObject(JarOutputRepositoryManager.java:78)
	at com.redhat.ceylon.compiler.java.tools.CeyloncFileManager.getFileForOutput(CeyloncFileManager.java:173)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$BuildFileManager.getFileForOutput(CeylonBuilder.java:384)
	at com.redhat.ceylon.langtools.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:752)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.addResources(LanguageCompiler.java:329)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.close(LanguageCompiler.java:315)
	at com.redhat.ceylon.langtools.tools.javac.main.JavaCompiler.close(JavaCompiler.java:1681)
	at com.redhat.ceylon.langtools.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:863)
	at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:259)
	at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
	at com.redhat.ceylon.langtools.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:132)
	at com.redhat.ceylon.langtools.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:141)
	at com.redhat.ceylon.compiler.java.tools.CeyloncTaskImpl.call(CeyloncTaskImpl.java:59)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.compile(CeylonBuilder.java:2595)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.generateBinaries(CeylonBuilder.java:2332)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.access$200(CeylonBuilder.java:208)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:1073)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder$4.call(CeylonBuilder.java:1070)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.doWithCeylonModelCaching(CeylonBuilder.java:258)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:1070)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:496)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:415)
	at com.redhat.ceylon.eclipse.core.classpath.BuildProjectAfterClasspathChangeJob.run(BuildProjectAfterClasspathChangeJob.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
``

**Comment by gavinking** [comment]
Is this really a bug in the IDE, or does it also occur with the CLI?

**Comment by jpragey** [comment]
Well, after re-checking, the bug occurs also in CLI if the faulty dir is inside a module (`resource/mymodule/static/file.html`), and in Eclipse wherever it is.
So this bug should be moved to `ceylon`. Is there an easy way to do it ?

**Comment by gavinking** [comment]
Not really, just open a new issue and close this one.

**Comment by jpragey** [comment]
Moved to https://github.com/ceylon/ceylon/issues/6231
