### ISSUE TITLE
confusing error running Java code that calls Ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1778]
I have a Java project that depends on a Ceylon project, and I've exported the Ceylon classpath containers.

I attempt to run the following Java class:

```java
package javaproj;

import ceylon.language.print_;

public class Clz {

    public static void main(String[] args) {
        print_.print("hello");
    }

}
```

And I get this error:

```
!ENTRY org.eclipse.core.jobs 4 2 2016-04-27 12:50:08.239
!MESSAGE An internal error occurred during: "Launching Clz".
!STACK 0
com.redhat.ceylon.common.tool.ToolUsageError: Module conflict error prevented classpath generation: try running "ceylon info --print-overrides nodetest/1.0.0" to display an override file you can use with "ceylon classpath --overrides override.xml nodetest/1.0.0" or try with "ceylon classpath --force nodetest/1.0.0" to select the latest versions
	at com.redhat.ceylon.tools.moduleloading.ModuleLoadingTool.errorOnConflictingModule(ModuleLoadingTool.java:138)
	at com.redhat.ceylon.tools.classpath.CeylonClasspathTool.run(CeylonClasspathTool.java:62)
	at com.redhat.ceylon.eclipse.core.launch.ClassPathEnricher$impl$1moduleClassPath_.moduleClassPath(CeylonAwareLaunchConfiguration.ceylon:155)
	at com.redhat.ceylon.eclipse.core.launch.ClassPathEnricher$impl$4.$call$(CeylonAwareLaunchConfiguration.ceylon:163)
	at com.redhat.ceylon.eclipse.core.launch.ClassPathEnricher$impl$4.$call$(CeylonAwareLaunchConfiguration.ceylon:162)
	at ceylon.language.Iterable$impl$3$1.next(Iterable.ceylon:357)
	at ceylon.language.expand_$1$1.it(expand.ceylon:21)
	at ceylon.language.expand_$1$1.$iterator$1(expand.ceylon:21)
	at ceylon.language.expand_$1$1.val(expand.ceylon:21)
	at ceylon.language.expand_$1$1.next(expand.ceylon:21)
	at ceylon.language.Iterable$impl$10$1.e(Iterable.ceylon:1162)
	at ceylon.language.Iterable$impl$10$1.$next$1(Iterable.ceylon:1162)
	at ceylon.language.Iterable$impl$10$1.next(Iterable.ceylon:1162)
	at ceylon.language.Iterable$impl$3$1.elem(Iterable.ceylon:357)
	at ceylon.language.Iterable$impl$3$1.next(Iterable.ceylon:357)
	at ceylon.language.Iterable$impl$10$1.e(Iterable.ceylon:1162)
	at ceylon.language.Iterable$impl$10$1.$next$1(Iterable.ceylon:1162)
	at ceylon.language.Iterable$impl$10$1.next(Iterable.ceylon:1162)
	at ceylon.collection.HashSet.addAll(HashSet.ceylon:256)
	at com.redhat.ceylon.eclipse.core.launch.ClassPathEnricher$impl.enrichClassPath(CeylonAwareLaunchConfiguration.ceylon:169)
	at com.redhat.ceylon.eclipse.core.launch.CeylonAwareJavaLaunchDelegate.enrichClassPath(CeylonAwareLaunchConfiguration.ceylon)
	at com.redhat.ceylon.eclipse.core.launch.CeylonAwareJavaLaunchDelegate.getClasspath(CeylonAwareLaunchConfiguration.ceylon:210)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:72)
	at com.redhat.ceylon.eclipse.core.launch.CeylonAwareJavaLaunchDelegate.originalLaunch(CeylonAwareLaunchConfiguration.ceylon:207)
	at com.redhat.ceylon.eclipse.core.launch.CeylonAwareLaunchConfigurationDelegate$impl.launch(CeylonAwareLaunchConfiguration.ceylon:109)
	at com.redhat.ceylon.eclipse.core.launch.CeylonAwareJavaLaunchDelegate.launch(CeylonAwareLaunchConfiguration.ceylon:199)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This might be because I have not done whatever magical invocations of the `Main` API are necessary, but, if so, a much better error message is necessary.

**Comment by FroMage** [comment]
Weird, I did get that to work without any metamodel set up. Sounds like your Ceylon module has dependencies, no?

**Comment by davidfestal** [comment]
It's probably not related to metamodel registering. But to the dependencies
of the Ceylon project.
Le 27 avr. 2016 13:01, "Stéphane Épardaud" <notifications@github.com> a
écrit :

Weird, I did get that to work without any metamodel set up. Sounds like
your Ceylon module has dependencies, no?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ceylon/ceylon-ide-eclipse/issues/1778#issuecomment-215049862>

**Comment by gavinking** [comment]
Sorry, false alarm, and I'm a retard. This was indeed a side-effect of the flat classpath (my module transitively imported two different versions of `ceylon.collection`), and so the error message was exactly correct.


However, it would be rather nice if the error would have pointed me to *which* module was the cause of the problem!

**Comment by gavinking** [comment]
@FroMage do you think we could at least improve the error message?

**Comment by FroMage** [comment]
I bet that message was printed on stderr. That tool was meant to be used as a tool, and it's reused programmatically so the error ended up in a place where it was lost. You could open an issue in the IDE so that we create an API for getting this classpath rather than reusing the tool itself.
