### ISSUE TITLE
NPE creating source folder in compiler-js project

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1796]
When I tried to create a new Ceylon module in `compiler-js`, and in that dialog create a new source folder `src/main/ceylon`, I got this unhandled event loop exception:
```
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.code.navigator.GenerateBuildPathActionGroup.alsoManageCeylonConfigFile(GenerateBuildPathActionGroup.java:340)
	at com.redhat.ceylon.eclipse.code.wizard.NewUnitWizardPage$6.widgetSelected(NewUnitWizardPage.java:359)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
```

**Comment by gavinking** [comment]
But `compiler-js` isn't a Ceylon project, is it?

**Comment by lucaswerkmeister** [comment]
No… should the “create new module” option be completely disabled?

**Comment by gavinking** [comment]
Should be fixed.

**Comment by lucaswerkmeister** [comment]
Thanks.
