### ISSUE TITLE
NPE while typing in the Open Type dialog

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#1833]
Was working fine for a few days, then suddenly I get `An internal error occurred during: "Items filtering".`

```
java.lang.NullPointerException
	at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.estimateWork(OpenDeclarationDialog.java:1135)
	at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.fillContentProvider(OpenDeclarationDialog.java:897)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2270)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2221)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2193)
	at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2180)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
Restarting Eclipse didn't help

Eclipse Neon, Ceylon IDE 1.3.0v20160916-1407-Final, Windows 10

**Comment by gavinking** [comment]
@davidfestal I'm giving this one to you, because I don't understand in what circumstances `CeylonProject.getModules()` is allowed to return `null`. The code is:

```ceylon
    shared actual Modules? modules =>
            if (exists tcMods = typechecker?.phasedUnits?.moduleManager?.modules)
            then
            object extends Modules() {
                typecheckerModules = tcMods;
            }
            else
            null;
```

**Comment by davidfestal** [comment]
`Modules` can be `null` at the start of a full build, or before every project has been built at least once.
