### ISSUE TITLE
An internal error occurred during: "Retrieving Fixes"

### ISSUE THREAD

**Issue by ncorai** [ceylon/ceylon-ide-eclipse#1834]
When hovering a missing type in the Ceylon IDE _editor_, the popup displays the above error message.

The Eclipse log contains the following stack trace:

```
org.eclipse.jface.text.BadLocationException
    at org.eclipse.jface.text.ListLineTracker.getLineInformation(ListLineTracker.java:172)
    at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:133)
    at org.eclipse.jface.text.AbstractDocument.getLineInformation(AbstractDocument.java:877)
    at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineInformation(SynchronizableDocument.java:287)
    at com.redhat.ceylon.eclipse.code.correct.EclipseDocument.getLineStartOffset(EclipseDocument.ceylon:18)
    at com.redhat.ceylon.ide.common.correct.createTypeParameterQuickFix_.addProposal$priv$(createTypeParameterQuickFix.ceylon:220)
    at com.redhat.ceylon.ide.common.correct.createTypeParameterQuickFix_.addCreateTypeParameterProposal(createTypeParameterQuickFix.ceylon:183)
    at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addCreationProposals$priv$(IdeQuickFixManager.ceylon:291)
    at com.redhat.ceylon.ide.common.correct.ideQuickFixManager_.addQuickFixes(IdeQuickFixManager.ceylon:29)
    at com.redhat.ceylon.eclipse.code.correct.correctJ2C.addQuickFixes(correctJ2C.java:76)
    at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.addProposals(CeylonCorrectionProcessor.java:525)
    at com.redhat.ceylon.eclipse.code.correct.CeylonCorrectionProcessor.collectCorrections(CeylonCorrectionProcessor.java:406)
    at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.collectProposals(AnnotationInfo.java:143)
    at com.redhat.ceylon.eclipse.code.hover.AnnotationInfo.getCompletionProposals(AnnotationInfo.java:96)
    at com.redhat.ceylon.eclipse.code.hover.AnnotationInformationControl$2.run(AnnotationInformationControl.java:262)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

In the _Problems_ view, the compile error for that type reference is `type is not defined: 'Foo' might be misspelled or is not imported` ~~(I'm not sure why Ceylon IDE couldn't read it from a .car file in a module repository that's within the project and configured in the project _lookup repositories_)~~

Edit: removed invalid context info - the type wasn't read from the .car file because I'm importing version 1.2 whereas the one present in the repository is 1.0

**Comment by gavinking** [comment]
@davidfestal I'm handing this one to you.

**Comment by bjansen** [comment]
It's possible that `BadLocationException`s were previously caught by the Java quick fixes, and are now ignored by the code I ported in ceylon-ide-common (i.e. we should catch them again, probably in `CeylonCorrectionProcessor`).

**Comment by gavinking** [comment]
I could not really see what was wrong with the code, but I have added a `catch` for the exception. Should be fixed.
