### ISSUE TITLE
NPE in the `OpenDeclarationDialog`

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1850]
```
java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.uniqueIdentifier(OpenDeclarationDialog.java:1179)
    at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.estimateWork(OpenDeclarationDialog.java:1144)
    at com.redhat.ceylon.eclipse.code.open.OpenDeclarationDialog.fillContentProvider(OpenDeclarationDialog.java:897)
    at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2270)
    at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2221)
    at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2193)
    at com.redhat.ceylon.eclipse.code.open.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2180)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
Thanks David!
