### ISSUE TITLE
Unable to open project because java.lang.LinkageError: org/apache/http/params/HttpParams

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1873]
This occurs trying to open the project https://github.com/DiegoCoronel/ceylon-spring-boot

```java
java.lang.LinkageError: org/apache/http/params/HttpParams
	at org.apache.http.params.HttpConnectionParams.setConnectionTimeout(HttpConnectionParams.java:189)
	at org.eclipse.aether.transport.http.HttpTransporter.configureClient(HttpTransporter.java:166)
	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:138)
	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:93)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:341)
	at com.redhat.ceylon.cmr.resolver.aether.AetherResolverImpl.resolveArtifactWithDependencies(AetherResolverImpl.java:423)
	at com.redhat.ceylon.cmr.resolver.aether.AetherResolverImpl.getDependencies(AetherResolverImpl.java:344)
	at com.redhat.ceylon.cmr.maven.AetherUtils.fetchDependencies(AetherUtils.java:179)
	at com.redhat.ceylon.cmr.maven.AetherUtils.findDependencies(AetherUtils.java:129)
	at com.redhat.ceylon.cmr.maven.AetherUtils.findDependencies(AetherUtils.java:95)
	at com.redhat.ceylon.cmr.maven.AetherRepository.getArtifactResultInternal(AetherRepository.java:94)
	at com.redhat.ceylon.cmr.impl.AbstractRepository.getArtifactResult(AbstractRepository.java:127)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.toArtifactResult(AbstractNodeRepositoryManager.java:121)
	at com.redhat.ceylon.cmr.impl.RootRepositoryManager.getArtifactResult(RootRepositoryManager.java:116)
	at com.redhat.ceylon.cmr.impl.AbstractNodeRepositoryManager.getArtifactResult(AbstractNodeRepositoryManager.java:185)
	at com.redhat.ceylon.cmr.ceylon.loader.BaseModuleLoaderImpl$ModuleLoaderContext.loadModule(BaseModuleLoaderImpl.java:215)
	at com.redhat.ceylon.cmr.ceylon.loader.BaseModuleLoaderImpl$ModuleLoaderContext.loadModule(BaseModuleLoaderImpl.java:246)
	at com.redhat.ceylon.cmr.ceylon.loader.BaseModuleLoaderImpl$ModuleLoaderContext.loadModule(BaseModuleLoaderImpl.java:246)
	at com.redhat.ceylon.cmr.ceylon.loader.BaseModuleLoaderImpl$ModuleLoaderContext.preloadModules(BaseModuleLoaderImpl.java:63)
	at com.redhat.ceylon.compiler.java.loader.CompilerModuleLoader$CompilerModuleLoaderContext.initialise(CompilerModuleLoader.java:58)
	at com.redhat.ceylon.cmr.ceylon.loader.BaseModuleLoaderImpl.loadModule(BaseModuleLoaderImpl.java:407)
	at com.redhat.ceylon.compiler.java.loader.model.LazyModuleSourceMapper.preResolveDependenciesIfRequired(LazyModuleSourceMapper.java:349)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator$2.run(ModuleValidator.java:104)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithExplicitCaching(TypeCache.java:50)
	at com.redhat.ceylon.model.typechecker.context.TypeCache.doWithoutCaching(TypeCache.java:75)
	at com.redhat.ceylon.compiler.typechecker.analyzer.ModuleValidator.verifyModuleDependencyTree(ModuleValidator.java:97)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16$1.$call$(CeylonProject.ceylon:963)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProject$16.$call$(CeylonProject.ceylon:800)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:496)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:488)
	at com.redhat.ceylon.ide.common.model.CeylonProject.parseCeylonModel(CeylonProject.ceylon:797)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:914)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
@DiegoCoronel I don't experience this. It's working for me.

**Comment by CPColin** [comment]
I ran into this a month ago and reported it here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466003#c3

Things worked fine once I deleted version 4.5.2 of `httpclient` and version 4.4.6 of `httpcore`.

**Comment by DiegoCoronel** [comment]
@CPColin tks for your answer, this is my current `.p2/pool/plugins` should i remove from this folder?

I tried to remove all `.p2` folder and install everything from 0 but Im having same issue and Im not able to use eclipse + ceylon anymore since this issue date :(

```
org.apache.commons.httpclient_3.1.0.v201012070820.jar
org.apache.httpcomponents.httpclient_4.3.2.CEYLON-DEPENDENCIES-v0
org.apache.httpcomponents.httpclient_4.5.2.v20170210-0925.jar
org.apache.httpcomponents.httpcore_4.3.2.CEYLON-DEPENDENCIES-v0
org.apache.httpcomponents.httpcore_4.4.6.v20170210-0925.jar
org.apache.maven.resolver.transport.http_1.0.3.v20170405-0725.jar
org.eclipse.aether.transport.http_1.1.0.CEYLON-DEPENDENCIES-v0
org.eclipse.ecf.provider.filetransfer.httpclient4.ssl_1.1.0.v20160817-1024.jar
org.eclipse.ecf.provider.filetransfer.httpclient4_1.1.200.v20170314-0133.jar
org.eclipse.equinox.http.jetty_3.4.0.v20170503-2025.jar
org.eclipse.equinox.http.registry_1.1.400.v20150715-1528.jar
org.eclipse.equinox.http.servlet_1.4.0.v20170524-1452.jar
org.eclipse.jetty.http_9.4.5.v20170502.jar
org.eclipse.mylyn.commons.repositories.http.core_1.15.0.v20170411-1844.jar
```

**Comment by CPColin** [comment]
Try deleting `org.apache.httpcomponents.httpclient_4.5.2.v20170210-0925.jar` and `org.apache.httpcomponents.httpcore_4.4.6.v20170210-0925.jar`.

**Comment by davidfestal** [comment]
Afair I was able to fix this by removing some of the `Recommenders` plugins added (more or less by default) in the last Eclipse releases.

**Comment by DiegoCoronel** [comment]
@CPColin it works \o/ .. Tks. @davidfestal or @gavinking should I close this issue ? I dont know if this something you can workaround in ceylon plugin
