### ISSUE TITLE
Latest plugin throws exceptions

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1879]
Latest plugin throws this left and right:

```
java.lang.NoSuchMethodError: com.redhat.ceylon.eclipse.code.outline.DecoratedImageDescriptor.getZoomLevel()I
	at com.redhat.ceylon.eclipse.code.outline.DecoratedImageDescriptor.imageData(DecoratedImageDescriptor.java:129)
	at com.redhat.ceylon.eclipse.code.outline.DecoratedImageDescriptor.getSize(DecoratedImageDescriptor.java:118)
	at org.eclipse.jface.resource.CompositeImageDescriptor.getImageData(CompositeImageDescriptor.java:164)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:270)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:164)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:52)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:86)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:204)
	at com.redhat.ceylon.eclipse.code.outline.CeylonLabelProvider.getDecoratedImage(CeylonLabelProvider.java:177)
	at com.redhat.ceylon.eclipse.code.navigator.CeylonNavigatorLabelProvider.getImage(CeylonNavigatorLabelProvider.java:250)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.findImage(NavigatorContentServiceLabelProvider.java:199)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getColumnImage(NavigatorContentServiceLabelProvider.java:107)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getImage(NavigatorContentServiceLabelProvider.java:99)
	at org.eclipse.ui.internal.navigator.NavigatorDecoratingLabelProvider$StyledLabelProviderAdapter.getImage(NavigatorDecoratingLabelProvider.java:57)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:195)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:168)
	at org.eclipse.ui.navigator.CommonNavigatorManager.updateStatusBar(CommonNavigatorManager.java:316)
	at org.eclipse.ui.navigator.CommonNavigatorManager$1.selectionChanged(CommonNavigatorManager.java:75)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1244)
	at org.eclipse.ui.navigator.CommonViewer.handlePostSelect(CommonViewer.java:457)
	at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1270)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
	at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:431)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4528)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4146)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by FroMage** [comment]
Blocks 1.3.3

**Comment by gavinking** [comment]
@FroMage I'm pretty sure this must be because you're not on Oxygen.

**Comment by FroMage** [comment]
Yes, but is it a requirement now?

**Comment by FroMage** [comment]
Also note that since I upgraded the Ceylon plugin this morning, my Eclipse's all broken and has redraw issues, including flickering :( Not just in the Ceylon mode.

**Comment by gavinking** [comment]
Yes, Oxygen is 100% required for 1.3.3.

**Comment by FroMage** [comment]
ah, ok, I guess I have to upgrade then

**Comment by FroMage** [comment]
shouldn't the plugin say so and refuse to install then?

**Comment by gavinking** [comment]
> shouldn't the plugin say so and refuse to install then?

It's a real surprise to me that it doesn't.

So yeah.

Perhaps there is some item of metadata we need to change?

**Comment by FroMage** [comment]
Surely, but no idea where.

**Comment by gavinking** [comment]
No, I'm searching, and I have not found anything obvious.
