### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-eclipse#1880]
Just got this in the logs:

```
ceylon.language.AssertionError "null value returned from native call not assignable to Object"
	at com.redhat.ceylon.compiler.java.Util.checkNull(Util.java:1008)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$ModuleDescriptorDeltaBuilder$2.$evaluate$(deltaBuilder.ceylon:405)
	at com.redhat.ceylon.compiler.java.language.LazyIterable$LazyIterator.next(LazyIterable.java:49)
	at ceylon.language.any_.any(any.ceylon:11)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$ModuleDescriptorDeltaBuilder.calculateLocalChanges(deltaBuilder.ceylon:400)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$DeltaBuilder.recurse(deltaBuilder.ceylon:228)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory$ModuleDescriptorDeltaBuilder.buildDelta(deltaBuilder.ceylon:361)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildModuleDescriptorDeltas$priv$(deltaBuilder.ceylon:117)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas$canonical$(deltaBuilder.ceylon:86)
	at com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas(deltaBuilder.ceylon:82)
	at com.redhat.ceylon.ide.common.model.ProjectSourceFile.buildDeltaAgainstModel(ProjectSourceFile.ceylon:147)
	at com.redhat.ceylon.eclipse.core.builder.DeltaScanner.visit(DeltaScanner.java:149)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.chooseBuildTypeFromDeltas(CeylonBuilder.java:1603)
	at com.redhat.ceylon.eclipse.core.builder.CeylonBuilder.build(CeylonBuilder.java:846)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:487)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:406)
	at com.redhat.ceylon.eclipse.core.classpath.BuildProjectAfterClasspathChangeJob.run(BuildProjectAfterClasspathChangeJob.java:59)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gavinking** [comment]
Have not seen this one; I'll take a look.

**Comment by gavinking** [comment]
@FroMage it should be fixed by https://github.com/ceylon/ceylon-ide-common/commit/5422b0cdd230f2fed43cf207c81a3e62a9b63242.

**Comment by gavinking** [comment]
Can you verify, please?
